package index

import (
	"bytes"
	"regexp"
	"strings"
)

// Generated-file detection follows the convention established by codegraph
// (generated-detection.ts): generated sources are ranked below hand-written
// implementations during disambiguation because generated stubs frequently
// reuse the exact names of real symbols (protobuf scaffolding, test mocks,
// codegen output) and otherwise drown them out of search results. This is a
// relevance hint, not a hard filter — generated nodes stay indexed and
// reachable; they just rank last when a real implementation shares the name.
//
// Two signals, deliberately separate:
//
//  1. IsGeneratedPath — PATH only, pure and synchronous. Most generated files
//     follow the `<basename>.<tool>.<ext>` convention (`.pb.go`, `.g.dart`,
//     `_pb2.py`).
//
//  2. isGeneratedContent — CONTENT banner in the file's head. Go's own
//     convention is a content marker ("// Code generated ... DO NOT EDIT."),
//     so a generated file with a hand-written-looking name is invisible to
//     (1). Evaluated ONCE at index time, when the source is already in
//     memory, and persisted on the index as GeneratedFiles.

var generatedPathPatterns = []*regexp.Regexp{
	// Go — protobuf / gRPC / pulsar / mockgen
	regexp.MustCompile(`\.pb\.go$`),
	regexp.MustCompile(`\.pulsar\.go$`),
	regexp.MustCompile(`_grpc\.pb\.go$`),
	regexp.MustCompile(`_mock\.go$`),
	regexp.MustCompile(`_mocks\.go$`),
	regexp.MustCompile(`^mock_[^/]+\.go$`),
	// TypeScript / JavaScript — codegen suffixes (GraphQL, Prisma, ts-proto,
	// gRPC-web, swagger-codegen) plus vendored minified bundles.
	regexp.MustCompile(`\.generated\.[jt]sx?$`),
	regexp.MustCompile(`\.gen\.[jt]sx?$`),
	regexp.MustCompile(`\.pb\.[jt]s$`),
	regexp.MustCompile(`_pb\.[jt]s$`),
	regexp.MustCompile(`_grpc_pb\.[jt]s$`),
	regexp.MustCompile(`\.min\.m?js$`),
	// Python — protobuf / gRPC / openapi-codegen
	regexp.MustCompile(`_pb2(_grpc)?\.py$`),
	regexp.MustCompile(`_pb2\.pyi$`),
	// C++ — protobuf
	regexp.MustCompile(`\.pb\.(cc|h)$`),
	// C# — protobuf / gRPC / WinForms designer
	regexp.MustCompile(`\.g\.cs$`),
	regexp.MustCompile(`Grpc\.cs$`),
	// Java — protobuf / gRPC
	regexp.MustCompile(`OuterClass\.java$`),
	regexp.MustCompile(`Grpc\.java$`),
	// Swift / Dart / Rust — protobuf, build_runner, codegen
	regexp.MustCompile(`\.pb\.swift$`),
	regexp.MustCompile(`\.g\.dart$`),
	regexp.MustCompile(`\.freezed\.dart$`),
	regexp.MustCompile(`\.pb\.dart$`),
	regexp.MustCompile(`\.pbgrpc\.dart$`),
	regexp.MustCompile(`\.chopper\.dart$`),
	regexp.MustCompile(`\.generated\.rs$`),
}

// IsGeneratedPath reports whether a file path looks like tool-generated source
// based on its filename alone. Path-only — does not read content. Patterns are
// tested against both the full path and the basename, so `mock_client.go`
// matches whether it sits at the root or under `generated/`.
func IsGeneratedPath(path string) bool {
	base := path
	if i := strings.LastIndexByte(path, '/'); i >= 0 {
		base = path[i+1:]
	}
	for _, re := range generatedPathPatterns {
		if re.MatchString(path) || re.MatchString(base) {
			return true
		}
	}
	return false
}

const (
	headerScanChars = 8192
	headerScanLines = 60
)

// generatedStem is a cheap pre-filter: every banner contains the stem
// "generat", so one scan rejects nearly all hand-written source before any
// line splitting happens.
var generatedStem = regexp.MustCompile(`(?i)generat`)

// commentLeader matches a line that begins with a line-comment leader across
// the languages we index; a generator always emits its banner as a comment,
// and requiring one rules out string literals that merely contain the words.
var commentLeader = regexp.MustCompile(`^\s*(?://|/\*+|\*+/|#+|--+|<!--|%+|;+|'|!|\(\*|\{-|"""|'''|=begin|<#|@rem|rem\b)`)

// generatedContentPatterns are real banners emitted by widely used generators.
// Precision-first: a false positive silently demotes hand-written code.
var generatedContentPatterns = []*regexp.Regexp{
	// Go's codified convention from `go generate` (protoc-gen-go, mockgen,
	// sqlc, ent, wire, stringer) — and in-house generators whose output is
	// named like hand-written source.
	regexp.MustCompile(`(?i)\bcode generated\b.{0,200}?\bdo not edit\b`),
	// protoc / ANTLR / Dagger / FlatBuffers / rust-bindgen / Xcode catalogs.
	regexp.MustCompile(`(?i)\b(?:automatically |auto[- ]?)?generated (?:by|from|with)\b.{0,200}?\bdo not (?:edit|modify|change)\b`),
	// The `@generated` marker (Relay, GraphQL codegen, protobuf-es). Guarded
	// so only a standalone tag matches, not `foo@generated`.
	regexp.MustCompile(`(?:^|[^\p{L}\p{N}_@])@generated\b`),
	// .NET's `<auto-generated>` doc tag (Roslyn, WinForms designer, T4).
	regexp.MustCompile(`(?i)<auto-?generated\s*/?>`),
	// OpenAPI Generator / Thrift / FlatBuffers; "by" required so ordinary
	// prose like "generated at runtime" never matches.
	regexp.MustCompile(`(?i)\b(?:automatically generated|auto[- ]?generated|autogenerated) by\b`),
	// "Generated by <tool> by running ..." (Wrangler et al.).
	regexp.MustCompile(`(?i)\bgenerated by\s+\S.{0,80}?\bby running\b`),
	// Self-declaring in-house banners that name no tool.
	regexp.MustCompile(`(?i)\bthis (?:file|class|code|module) (?:is|was) (?:auto[- ]?)?generated\b`),
	// Reverse ordering: "DO NOT EDIT — this is a generated file".
	regexp.MustCompile(`(?i)\bdo not (?:edit|modify)\b.{0,120}?\b(?:auto[- ]?generated|generated file|generated code)\b`),
}

// isGeneratedContent reports whether the head of src carries a generated-file
// banner on a comment line. It scans at most the first 8KB / 60 lines, so the
// cost stays off the index-time budget for the common (non-generated) case.
func isGeneratedContent(src []byte) bool {
	if len(src) == 0 || !generatedStem.Match(src) {
		return false
	}
	head := src
	if len(head) > headerScanChars {
		head = head[:headerScanChars]
	}
	lines := bytes.Split(head, []byte("\n"))
	if len(lines) > headerScanLines {
		lines = lines[:headerScanLines]
	}
	inBlock := false
	for _, line := range lines {
		s := string(line)
		if inBlock {
			if strings.Contains(s, "*/") || strings.Contains(s, "-->") {
				inBlock = false
			}
			if strings.Contains(s, "generat") && matchesAny(s, generatedContentPatterns) {
				return true
			}
			continue
		}
		if !commentLeader.MatchString(s) {
			// Stay inside an open block comment that started on a prior line.
			if strings.Contains(s, "/*") || strings.Contains(s, "<!--") || strings.Contains(s, `"""`) || strings.Contains(s, `'''`) {
				inBlock = true
			}
			continue
		}
		if matchesAny(s, generatedContentPatterns) {
			return true
		}
	}
	return false
}

func matchesAny(s string, patterns []*regexp.Regexp) bool {
	for _, re := range patterns {
		if re.MatchString(s) {
			return true
		}
	}
	return false
}
