package index

import (
	"strings"
	"testing"
)

func TestIsGeneratedPath(t *testing.T) {
	generated := []string{
		"api/foo.pb.go",
		"api/foo_grpc.pb.go",
		"api/foo.pulsar.go",
		"internal/mocks/mock_store.go",
		"internal/mocks/expected_mocks.go",
		"generated/mock_client.go",
		"schema/types.generated.ts",
		"schema/types.gen.js",
		"schema/model.pb.js",
		"proto/foo_pb2.py",
		"proto/foo_pb2_grpc.py",
		"build/foo.pb.cc",
		"app/foo.g.cs",
		"app/FooGrpc.cs",
		"generated/FooOuterClass.java",
		"generated/BarGrpc.java",
		"proto/foo.pb.swift",
		"models/foo.g.dart",
		"models/foo.freezed.dart",
		"models/foo.chopper.dart",
		"vendor/foo.min.js",
		"dist/bundle.min.mjs",
		"src/foo.generated.rs",
	}
	for _, p := range generated {
		if !IsGeneratedPath(p) {
			t.Errorf("IsGeneratedPath(%q) = false, want true", p)
		}
	}
	handWritten := []string{
		"main.go",
		"internal/store/store.go",
		"store_mock_adapter.go", // _mock in the middle, not the suffix
		"components/Button.tsx",
		"app/helpers.py",
		"src/notgenerated.rs",
	}
	for _, p := range handWritten {
		if IsGeneratedPath(p) {
			t.Errorf("IsGeneratedPath(%q) = true, want false", p)
		}
	}
}

func TestIsGeneratedContent(t *testing.T) {
	cases := []struct {
		name string
		src  string
		want bool
	}{
		{
			name: "go code generated banner",
			src:  "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage api\n",
			want: true,
		},
		{
			name: "go docstring containing phrase",
			src:  "// This helper generates code at runtime; do not edit it manually.\npackage main\n",
			want: false,
		},
		{
			name: "atsign generated marker",
			src:  "// @generated SignedSource<<abc123>>\n\nexport const x = 1;\n",
			want: true,
		},
		{
			name: "dotnet autogenerated tag",
			src:  "// <auto-generated>\nnamespace Foo { }\n",
			want: true,
		},
		{
			name: "hand-written",
			src:  "package main\n\n// Greet says hello.\nfunc Greet() {}\n",
			want: false,
		},
		{
			name: "generated by running",
			src:  "// Generated by Wrangler by running `wrangler types` (hash: abc)\nexport {};\n",
			want: true,
		},
	}
	for _, c := range cases {
		if got := isGeneratedContent([]byte(c.src)); got != c.want {
			t.Errorf("%s: isGeneratedContent = %v, want %v", c.name, got, c.want)
		}
	}
}

func TestIsMinified(t *testing.T) {
	cases := []struct {
		name string
		src  string
		want bool
	}{
		{
			name: "normal js short lines",
			src:  "function foo() {\n  const x = 1;\n  return x;\n}\n",
			want: false,
		},
		{
			name: "minified single 10000-char line",
			src:  strings.Repeat("a", 10000) + "\n",
			want: true,
		},
		{
			name: "minified many 600-char lines",
			src:  strings.Repeat("x", 600) + "\n" + strings.Repeat("y", 600) + "\n" + strings.Repeat("z", 600) + "\n" + strings.Repeat("w", 600) + "\n" + strings.Repeat("v", 600) + "\n" + strings.Repeat("u", 600) + "\n" + strings.Repeat("t", 600) + "\n" + strings.Repeat("s", 600) + "\n" + strings.Repeat("r", 600) + "\n" + strings.Repeat("q", 600) + "\n" + strings.Repeat("p", 600) + "\n",
			want: true,
		},
		{
			name: "empty file",
			src:  "",
			want: false,
		},
		{
			name: "python normal lines",
			src:  "def hello():\n    print('hi')\n",
			want: false,
		},
		{
			name: "few 600-char lines not enough",
			src:  strings.Repeat("x", 600) + "\n" + strings.Repeat("y", 600) + "\n" + strings.Repeat("z", 600) + "\n",
			want: false,
		},
	}
	for _, c := range cases {
		if got := isMinified([]byte(c.src)); got != c.want {
			t.Errorf("%s: isMinified = %v, want %v", c.name, got, c.want)
		}
	}
}

func TestBuildMarksGeneratedFiles(t *testing.T) {
	root := writeTree(t, map[string]string{
		"go.mod":             "module demo\n\ngo 1.22\n",
		"main.go":            "package main\n\nfunc Real() {}\n\nfunc main() { Real() }\n",
		"api/api.pb.go":      "package api\n\n// Code generated by protoc-gen-go. DO NOT EDIT.\nfunc Stub() {}\n",
		"models/types.pb.ts": "// @generated\nexport interface Foo {}\n",
	})
	ix, err := Build(root)
	if err != nil {
		t.Fatal(err)
	}
	if !ix.IsGenerated("api/api.pb.go") {
		t.Error("expected .pb.go path + banner to be marked generated")
	}
	if !ix.IsGenerated("models/types.pb.ts") {
		t.Error("expected .pb.ts path to be marked generated")
	}
	if ix.IsGenerated("main.go") {
		t.Error("main.go should not be marked generated")
	}
}
