// Package fw holds kern's built-in framework catalog: which frameworks each
// language has (Spring/Spring Boot for Java, Django/Flask/FastAPI for Python,
// Express/NestJS for TypeScript, Rails for Ruby, ...), the signals that reveal
// them in a project, and project-level detection over those signals.
// The catalog is the single source of truth for framework IDs used by the
// indexer's framework-aware symbol extraction (entry points, routes, handlers)
// and by `kern fw`, which answers "what stack is this project running?".
package fw

import "sort"

// Framework describes one framework and the signals that reveal it in a
// project. A framework is detected when any of its signals matches.
type Framework struct {
	ID      string   `json:"id"`   // stable id, e.g. "spring-boot"
	Name    string   `json:"name"` // display name, e.g. "Spring Boot"
	Lang    string   `json:"lang"` // normalized language key (index terms)
	Summary string   `json:"summary,omitempty"`
	Files   []string `json:"files,omitempty"` // path suffixes that mark the framework
	Deps    []string `json:"deps,omitempty"`  // substrings looked up in manifest files
	Code    []string `json:"code,omitempty"`  // substrings looked up in source files
}

// Detected is a framework found in a project plus the concrete signals that
// matched, for human-facing output.
type Detected struct {
	Framework
	Signals []string `json:"signals"`
}

func fw(id, name, lang, summary string, files, deps, code []string) Framework {
	return Framework{ID: id, Name: name, Lang: lang, Summary: summary, Files: files, Deps: deps, Code: code}
}

// Catalog returns every framework, grouped implicitly by Lang.
func Catalog() []Framework { return catalog }

// ByID returns the framework with the given id, or nil.
func ByID(id string) *Framework {
	for i := range catalog {
		if catalog[i].ID == id {
			return &catalog[i]
		}
	}
	return nil
}

// ByLang returns the frameworks for a normalized language key.
func ByLang(lang string) []Framework {
	var out []Framework
	for _, f := range catalog {
		if f.Lang == lang {
			out = append(out, f)
		}
	}
	return out
}

// Langs returns the distinct languages present in the catalog, sorted.
func Langs() []string {
	set := map[string]bool{}
	for _, f := range catalog {
		set[f.Lang] = true
	}
	out := make([]string, 0, len(set))
	for l := range set {
		out = append(out, l)
	}
	sort.Strings(out)
	return out
}

var catalog = []Framework{
	// ---------- Java ----------
	fw("spring-boot", "Spring Boot", "java",
		"Convention-over-configuration app framework built on Spring (the Java counterpart to a batteries-included stack).",
		nil,
		[]string{"spring-boot-starter", "<artifactId>spring-boot</", "spring-boot-maven-plugin"},
		[]string{"@SpringBootApplication", "SpringApplication.run"}),
	fw("spring-mvc", "Spring MVC", "java",
		"Spring Web MVC: annotation-driven controllers and REST endpoints.",
		nil,
		[]string{"spring-webmvc", "spring-boot-starter-web"},
		[]string{"@RestController", "@Controller", "@RequestMapping", "@GetMapping", "@PostMapping", "@PutMapping", "@DeleteMapping", "@PatchMapping"}),
	fw("spring-core", "Spring Framework", "java",
		"Spring core: dependency injection and configuration.",
		nil,
		[]string{"spring-context"},
		[]string{"@Service", "@Component", "@Autowired", "@Configuration", "@Bean"}),
	fw("spring-data-jpa", "Spring Data JPA", "java",
		"Spring data access over the JPA standard.",
		nil,
		[]string{"spring-data-jpa"},
		[]string{"@Repository", "@Entity", "@Id", "JpaRepository", "CrudRepository"}),
	fw("hibernate", "Hibernate", "java",
		"ORM/JPA implementation.",
		nil,
		[]string{"hibernate-core", "org.hibernate"},
		[]string{"@Entity", "@Table", "SessionFactory"}),
	fw("jakarta-ee", "Jakarta EE / JAX-RS", "java",
		"Jakarta REST (JAX-RS): @Path resources and HTTP verb annotations.",
		nil,
		[]string{"jakarta.ws.rs", "javax.ws.rs"},
		[]string{"@Path(", "@GET", "@POST", "@PUT", "@DELETE", "@ApplicationPath", "@Produces", "@Consumes"}),
	fw("lombok", "Lombok", "java",
		"Annotation-driven boilerplate removal.",
		nil,
		[]string{"org.projectlombok:lombok", "lombok"},
		[]string{"@Data", "@Getter", "@Setter", "@Builder", "@AllArgsConstructor", "@RequiredArgsConstructor"}),
	fw("mybatis", "MyBatis", "java",
		"SQL-mapping persistence framework.",
		nil,
		[]string{"mybatis", "org.mybatis"},
		[]string{"@Mapper", "@Select", "@Insert", "@Update", "@Delete"}),
	fw("junit", "JUnit", "java",
		"Unit-testing framework.",
		nil,
		[]string{"junit-jupiter", "junit:junit", "org.junit"},
		[]string{"@Test", "@org.junit", "Assertions."}),
	fw("kafka-java", "Kafka clients", "java",
		"Apache Kafka producer/consumer (incl. Spring Kafka listeners).",
		nil,
		[]string{"spring-kafka", "kafka-clients"},
		[]string{"@KafkaListener", "KafkaTemplate", "ConsumerRecord"}),

	// ---------- Python ----------
	fw("django", "Django", "python",
		"Full-stack web framework: batteries included.",
		[]string{"manage.py", "settings.py", "wsgi.py", "asgi.py", "urls.py"},
		[]string{"django"},
		[]string{"from django", "import django", "urlpatterns", "django.conf"}),
	fw("drf", "Django REST Framework", "python",
		"REST toolkit for Django.",
		nil,
		[]string{"djangorestframework", "django-rest-framework"},
		[]string{"from rest_framework", "rest_framework.serializers", "rest_framework.views"}),
	fw("flask", "Flask", "python",
		"Micro web framework.",
		nil,
		[]string{"flask"},
		[]string{"from flask", "import flask", "@app.route", "@app.get", "@app.post", "Flask("}),
	fw("fastapi", "FastAPI", "python",
		"Modern async REST framework with automatic OpenAPI.",
		nil,
		[]string{"fastapi"},
		[]string{"from fastapi", "import fastapi", "APIRouter(", "@app.get", "@app.post", "@router.get", "@router.post"}),
	fw("celery", "Celery", "python",
		"Distributed task queue.",
		nil,
		[]string{"celery"},
		[]string{"from celery", "import celery", "@app.task", "@shared_task"}),
	fw("sqlalchemy", "SQLAlchemy", "python",
		"SQL toolkit and ORM.",
		nil,
		[]string{"sqlalchemy"},
		[]string{"from sqlalchemy", "import sqlalchemy", "declarative_base", "Column("}),
	fw("pydantic", "Pydantic", "python",
		"Data validation using Python type hints.",
		nil,
		[]string{"pydantic"},
		[]string{"from pydantic", "import pydantic", "BaseModel"}),
	fw("tornado", "Tornado", "python",
		"Asynchronous networking framework.",
		nil,
		[]string{"tornado"},
		[]string{"tornado.web", "tornado.ioloop"}),
	fw("pytest", "pytest", "python",
		"Test framework.",
		nil,
		[]string{"pytest"},
		[]string{"import pytest", "from pytest"}),

	// ---------- JavaScript / TypeScript ----------
	fw("express", "Express", "js",
		"Minimal Node web framework.",
		nil,
		[]string{`"express"`, `'express'`},
		[]string{"from 'express'", `from "express"`, "require('express')", `require("express")`, "express()"}),
	fw("nestjs", "NestJS", "ts",
		"Structured Node framework with decorators.",
		nil,
		[]string{"@nestjs/core", "@nestjs/common"},
		[]string{"@nestjs", "@Controller(", "@Module(", "@Get()", "@Post()"}),
	fw("nextjs", "Next.js", "ts",
		"React framework with file-based routing.",
		[]string{"next.config.js", "next.config.mjs", "next.config.ts"},
		[]string{`"next"`},
		[]string{"from 'next'", `from "next"`, "next/dynamic"}),
	fw("react", "React", "js",
		"UI component library.",
		nil,
		[]string{`"react"`, `"react-dom"`},
		[]string{"from 'react'", `from "react"`, "require('react')", "useState(", "useEffect("}),
	fw("fastify", "Fastify", "js",
		"High-performance Node web framework.",
		nil,
		[]string{`"fastify"`},
		[]string{"from 'fastify'", `from "fastify"`, "require('fastify')", "fastify("}),
	fw("koa", "Koa", "js",
		"Next-generation Node web framework.",
		nil,
		[]string{`"koa"`},
		[]string{"from 'koa'", `from "koa"`, "require('koa')", "new Koa("}),
	fw("vue", "Vue", "js",
		"Progressive frontend framework.",
		[]string{".vue"},
		[]string{`"vue"`, `"@vue/`},
		[]string{"from 'vue'", `from "vue"`, "createApp("}),
	fw("svelte", "Svelte", "js",
		"Compiler-driven UI framework.",
		[]string{".svelte"},
		[]string{`"svelte"`, `"@sveltejs/kit"`},
		[]string{"from 'svelte'", `from "svelte"`, "<script lang="}),
	fw("angular", "Angular", "ts",
		"Full frontend framework.",
		nil,
		[]string{"@angular/core", "@angular/common"},
		[]string{"@angular/core", "@Component(", "@NgModule("}),
	fw("prisma", "Prisma", "ts",
		"Type-safe database ORM for Node.",
		nil,
		[]string{"@prisma/client", `"prisma"`},
		[]string{"from '@prisma/client'", `from "@prisma/client"`, "PrismaClient"}),
	fw("typeorm", "TypeORM", "ts",
		"ORM for TypeScript/JavaScript.",
		nil,
		[]string{"typeorm"},
		[]string{"typeorm", "Entity("}),
	fw("trpc", "tRPC", "ts",
		"End-to-end typesafe APIs.",
		nil,
		[]string{"@trpc/server"},
		[]string{"@trpc/server", "createTRPCRouter"}),
	fw("jest", "Jest", "js",
		"JavaScript test framework.",
		nil,
		[]string{`"jest"`},
		[]string{"describe(", `it("`, "it('", "expect("}),
	fw("vitest", "Vitest", "ts",
		"Vite-native test framework.",
		nil,
		[]string{`"vitest"`},
		[]string{"from 'vitest'", `from "vitest"`}),

	// ---------- Ruby ----------
	fw("rails", "Ruby on Rails", "ruby",
		"Full-stack web framework.",
		[]string{"config/application.rb", "bin/rails", "config/routes.rb", "app/controllers"},
		[]string{"rails"},
		[]string{"Rails.application", "rails/all", "ActiveRecord::Base"}),
	fw("sinatra", "Sinatra", "ruby",
		"Micro web framework.",
		nil,
		[]string{"sinatra"},
		[]string{"require 'sinatra'", `require "sinatra"`, "Sinatra::Base"}),
	fw("rspec", "RSpec", "ruby",
		"Behavior-driven testing framework.",
		nil,
		[]string{"rspec", "rspec-rails"},
		[]string{"RSpec.describe", "describe "}),
	fw("sidekiq", "Sidekiq", "ruby",
		"Background job processing.",
		nil,
		[]string{"sidekiq"},
		[]string{"Sidekiq::", "include Sidekiq::Worker"}),
	fw("grape", "Grape", "ruby",
		"REST-like API micro-framework.",
		nil,
		[]string{"grape"},
		[]string{"include Grape::API", "Grape::API"}),
	fw("activerecord", "ActiveRecord", "ruby",
		"ORM included with Rails.",
		nil,
		[]string{"activerecord"},
		[]string{"ActiveRecord::Base", "belongs_to ", "has_many "}),
	fw("devise", "Devise", "ruby",
		"Authentication solution.",
		nil,
		[]string{"devise"},
		[]string{"devise_for", "devise "}),

	// ---------- PHP ----------
	fw("laravel", "Laravel", "php",
		"Full-stack PHP framework.",
		[]string{"artisan", "config/app.php", "routes/web.php"},
		[]string{"laravel/framework", "illuminate/"},
		[]string{"Route::", "use Illuminate", "Illuminate\\"}),
	fw("symfony", "Symfony", "php",
		"PHP framework and reusable components.",
		nil,
		[]string{"symfony/", "symfony/framework-bundle"},
		[]string{"Symfony\\Component", "Symfony\\Bundle", "use Symfony"}),
	fw("laminas", "Laminas", "php",
		"Laminas (ex-Zend) MVC framework.",
		nil,
		[]string{"laminas/", "zendframework/"},
		[]string{"Laminas\\", "Zend\\"}),
	fw("codeigniter", "CodeIgniter", "php",
		"Lightweight PHP MVC framework.",
		nil,
		[]string{"codeigniter4/", "codeigniter/framework"},
		[]string{"CI_Controller", "CodeIgniter\\"}),
	fw("wordpress", "WordPress", "php",
		"Content management system.",
		[]string{"wp-content/", "wp-config.php", "wp-load.php"},
		nil,
		[]string{"add_action(", "add_filter(", "wp_head(", "get_header("}),

	// ---------- Go ----------
	fw("net-http", "net/http", "go",
		"Standard library HTTP server and routing.",
		nil,
		nil,
		[]string{"http.HandleFunc", "http.Handle(", "http.ListenAndServe", "http.NewServeMux", "http.Handler"}),
	fw("http-route", "Go HTTP router", "go",
		"Generic Go router (gin, echo, chi, fiber): verb-method routing.",
		nil,
		nil,
		[]string{"func(c *gin.Context)", "gin.Default()", "echo.New()", "chi.NewRouter()", "fiber.New()", "app.Listen("}),
	fw("gin", "Gin", "go",
		"High-performance HTTP framework.",
		nil,
		[]string{"gin-gonic/gin"},
		[]string{"gin.Default()", "gin.New()", "func(c *gin.Context)", "gin.Context"}),
	fw("echo", "Echo", "go",
		"High performance, minimalist Go web framework.",
		nil,
		[]string{"labstack/echo"},
		[]string{"echo.New()", "func(c echo.Context)", "echo.Context"}),
	fw("chi", "Chi", "go",
		"Composable router built on net/http.",
		nil,
		[]string{"go-chi/chi"},
		[]string{"chi.NewRouter()", "chi.NewMux()", "chi.URLParam"}),
	fw("fiber", "Fiber", "go",
		"Express-inspired web framework.",
		nil,
		[]string{"gofiber/fiber"},
		[]string{"fiber.New()", "fiber.Get(", "func(c *fiber.Ctx)"}),
	fw("grpc-go", "gRPC-Go", "go",
		"High-performance RPC framework.",
		nil,
		[]string{"google.golang.org/grpc"},
		[]string{"grpc.NewServer()", "grpc.Server", "protobuf"}),
	fw("cobra", "Cobra", "go",
		"CLI application framework.",
		nil,
		[]string{"spf13/cobra"},
		[]string{"cobra.Command", "cobra.NewCommand", "Use:   \""}),
	fw("gorm", "GORM", "go",
		"ORM library for Go.",
		nil,
		[]string{"gorm.io/gorm"},
		[]string{"gorm.Open", "gorm.DB", "gorm.Model"}),
	fw("sqlx", "sqlx", "go",
		"Extensions on database/sql.",
		nil,
		[]string{"jmoiron/sqlx"},
		[]string{"sqlx.Open", "sqlx.DB"}),
	fw("viper", "Viper", "go",
		"Configuration management.",
		nil,
		[]string{"spf13/viper"},
		[]string{"viper.SetConfigName", "viper.Get", "viper.AutomaticEnv"}),
	fw("testify", "Testify", "go",
		"Assertion and mocking toolkit.",
		nil,
		[]string{"stretchr/testify"},
		[]string{"testify/assert", "testify/require", "assert."}),

	// ---------- Rust ----------
	fw("actix-web", "Actix Web", "rust",
		"Powerful, pragmatic web framework.",
		nil,
		[]string{"actix-web"},
		[]string{"#[actix_web::main]", "#[get(", "#[post(", "HttpServer::new"}),
	fw("axum", "Axum", "rust",
		"Modular web framework built on tokio/tower.",
		nil,
		[]string{"axum"},
		[]string{"Router::new()", "Router::new(", ".route(", "axum::routing"}),
	fw("rocket", "Rocket", "rust",
		"Web framework with focus on ease of use.",
		nil,
		[]string{"rocket"},
		[]string{"#[rocket::main]", "#[get(", "#[post(", "rocket::build"}),
	fw("warp", "Warp", "rust",
		"Composable web server framework.",
		nil,
		[]string{"warp"},
		[]string{"warp::serve", "warp::path", "warp::filter"}),
	fw("tokio", "Tokio", "rust",
		"Async runtime.",
		nil,
		[]string{"tokio"},
		[]string{"#[tokio::main]", "tokio::spawn", "tokio::net"}),
	fw("serde", "Serde", "rust",
		"Serialization framework.",
		nil,
		[]string{"serde"},
		[]string{"#[derive(Serialize", "#[derive(Deserialize", "serde::"}),
	fw("diesel", "Diesel", "rust",
		"Safe, extensible ORM and query builder.",
		nil,
		[]string{"diesel"},
		[]string{"diesel::prelude", "diesel::insert"}),
	fw("clap", "Clap", "rust",
		"Command-line argument parser.",
		nil,
		[]string{"clap"},
		[]string{"#[derive(Parser)", "clap::Parser", "clap::Command"}),

	// ---------- C# ----------
	fw("aspnet-core", "ASP.NET Core", "csharp",
		"Web framework on .NET.",
		nil,
		[]string{"Microsoft.AspNetCore", "Microsoft.NET.Sdk.Web"},
		[]string{"[ApiController]", "app.MapGet", "app.MapPost", "IHostBuilder", "WebApplication.CreateBuilder"}),
	fw("ef-core", "EF Core", "csharp",
		"Entity Framework Core ORM.",
		nil,
		[]string{"Microsoft.EntityFrameworkCore"},
		[]string{"DbContext", "DbSet<"}),
	fw("maui", ".NET MAUI", "csharp",
		"Cross-platform UI framework.",
		nil,
		[]string{"Microsoft.Maui"},
		[]string{"Microsoft.Maui", "XamlC", "Application"}),
	fw("wpf", "WPF", "csharp",
		"Windows Presentation Foundation.",
		[]string{".xaml"},
		nil,
		[]string{"System.Windows", "[STAThread]"}),
	fw("xunit", "xUnit", "csharp",
		"Unit-testing framework.",
		nil,
		[]string{"xunit"},
		[]string{"[Fact]", "[Theory]", "Assert."}),

	// ---------- C / C++ ----------
	fw("qt", "Qt", "cpp",
		"Cross-platform C++ application framework.",
		[]string{".pro", "CMakeLists.txt"},
		nil,
		[]string{"#include <Qt", "#include <QApplication", "Q_OBJECT"}),
	fw("boost", "Boost", "cpp",
		"Peer-reviewed C++ libraries.",
		nil,
		nil,
		[]string{"#include <boost/"}),
	fw("grpc-cpp", "gRPC C++", "cpp",
		"RPC framework for C++.",
		nil,
		nil,
		[]string{"#include <grpcpp/", "grpcpp"}),
	fw("opencv", "OpenCV", "cpp",
		"Computer vision library.",
		nil,
		nil,
		[]string{"#include <opencv2/", "cv::Mat"}),
}
