package diffgate

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io/fs"
	"maps"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strings"

	"github.com/JayveerPrajapati/kern/internal/blueprint/domain"
)

// catalogDocRelPath is the repo-relative path (slash-separated) of the
// generated MCP tool catalog document.
const catalogDocRelPath = "docs/tool-catalog.md"

// GenerateCatalogDoc renders the MCP tool catalog as a deterministic
// markdown document: one section per tool, sorted by name, with phase, risk
// level, description, and the input-schema property keys. The output is
// byte-stable for a given catalog, so staleness is a content-hash compare.
func GenerateCatalogDoc(catalog []ToolInfo) []byte {
	sorted := append([]ToolInfo(nil), catalog...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Name < sorted[j].Name })

	var b bytes.Buffer
	b.WriteString("<!-- Generated by `kern gen-catalog` — do not edit by hand.\n")
	b.WriteString("     Run `kern gen-catalog` after adding, renaming, or changing an MCP tool.\n")
	b.WriteString("     The catalog:doc gate (G36) fails when this file is stale or a tool is missing. -->\n")
	b.WriteString("# MCP Tool Catalog\n\n")
	fmt.Fprintf(&b, "Every model-facing tool the kern MCP server registers (`kern_*`). %d tools.\n\n", len(sorted))
	b.WriteString("| Tool | Phase | Risk | Description |\n")
	b.WriteString("|---|---|---|---|\n")
	for _, t := range sorted {
		desc := strings.ReplaceAll(t.Description, "\n", " ")
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s |\n", t.Name, t.Phase, t.RiskLevel, desc)
	}
	b.WriteString("\n")
	for _, t := range sorted {
		fmt.Fprintf(&b, "## `%s`\n\n", t.Name)
		fmt.Fprintf(&b, "- Phase: `%s`\n- Risk: `%s`\n- Description: %s\n", t.Phase, t.RiskLevel, strings.ReplaceAll(t.Description, "\n", " "))
		keys := schemaPropertyKeys(t.InputSchema)
		if len(keys) > 0 {
			b.WriteString("- Input parameters: `" + strings.Join(keys, "`, `") + "`\n")
		} else {
			b.WriteString("- Input parameters: none\n")
		}
		b.WriteString("\n")
	}
	return b.Bytes()
}

// schemaPropertyKeys returns the sorted top-level property names of a JSON
// input schema, or nil when the schema has no properties.
func schemaPropertyKeys(schema map[string]any) []string {
	props, ok := schema["properties"].(map[string]any)
	if !ok {
		return nil
	}
	return slices.Sorted(maps.Keys(props))
}

// CatalogDocCheck (G36) verifies the committed docs/tool-catalog.md is
// present, covers every registered MCP tool, and is byte-identical to a
// fresh generation. It BLOCKs on any violation: a tool added without
// regenerating the catalog is silently undocumented, which is exactly the
// drift dsh's verify-tool-catalog guard prevents.
type CatalogDocCheck struct {
	root  string
	tools []ToolInfo
}

// NewCatalogDocCheck constructs the catalog-doc check bound to a repo root.
// tools is the injected live MCP catalog — mandatory (a wiring site that
// omits it fails to compile; an empty list fails loud at Run).
func NewCatalogDocCheck(root string, tools []ToolInfo) *CatalogDocCheck {
	return &CatalogDocCheck{root: root, tools: tools}
}

// WriteCatalogDoc regenerates docs/tool-catalog.md from the live MCP catalog
// and returns the written path. Errors when no catalog is injected.
func WriteCatalogDoc(root string, tools []ToolInfo) (string, error) {
	if err := requireCatalogTools(tools); err != nil {
		return "", err
	}
	docPath := filepath.Join(root, filepath.FromSlash(catalogDocRelPath))
	if err := os.MkdirAll(filepath.Dir(docPath), 0o755); err != nil {
		return "", err
	}
	if err := os.WriteFile(docPath, GenerateCatalogDoc(tools), 0o644); err != nil {
		return "", err
	}
	return docPath, nil
}

// Name is the stable check identifier.
func (c *CatalogDocCheck) Name() string { return "catalog:doc" }

// Run compares the committed catalog doc against the live MCP catalog.
func (c *CatalogDocCheck) Run(ctx context.Context, req domain.ChangeRequest) (domain.CheckResult, error) {
	if c.root == "" {
		return domain.CheckResult{Name: c.Name(), Status: domain.StatusError, Error: "repository root required"}, nil
	}
	if err := requireCatalogTools(c.tools); err != nil {
		return domain.CheckResult{Name: c.Name(), Status: domain.StatusError, Error: err.Error()}, nil
	}
	docPath := filepath.Join(c.root, filepath.FromSlash(catalogDocRelPath))
	committed, err := os.ReadFile(docPath)
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return domain.CheckResult{Name: c.Name(), Status: domain.StatusBlock, Error: fmt.Sprintf("generated tool catalog missing at %s — run `kern gen-catalog`", catalogDocRelPath)}, nil
		}
		return domain.CheckResult{Name: c.Name(), Status: domain.StatusError, Error: fmt.Sprintf("read %s: %v", docPath, err)}, nil
	}

	docText := string(committed)
	var missing []string
	for _, t := range c.tools {
		if !strings.Contains(docText, "`"+t.Name+"`") {
			missing = append(missing, t.Name)
		}
	}
	if len(missing) > 0 {
		return domain.CheckResult{Name: c.Name(), Status: domain.StatusBlock, Error: fmt.Sprintf("docs/tool-catalog.md does not document registered tool(s): %s — run `kern gen-catalog`", strings.Join(missing, ", "))}, nil
	}
	fresh := GenerateCatalogDoc(c.tools)
	if !bytes.Equal(committed, fresh) {
		return domain.CheckResult{Name: c.Name(), Status: domain.StatusBlock, Error: "docs/tool-catalog.md is stale or out of order — run `kern gen-catalog` and commit the regenerated file"}, nil
	}
	return domain.CheckResult{Name: c.Name(), Status: domain.StatusPass}, nil
}
