package diffgate

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io/fs"
	"maps"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strings"

	"github.com/JayveerPrajapati/kern/internal/blueprint/domain"
)

// contractsDocRelPath is the repo-relative path (slash-separated) of the
// generated MCP tool contracts document.
const contractsDocRelPath = "docs/mcp/tool-contracts.md"

// contractPhases is the canonical phase order used by the detailed-contracts
// sections, with the established section labels.
var contractPhases = []struct {
	name  string
	label string
}{
	{"explore", "Explore — read / discover"},
	{"plan", "Plan — analyze / simulate"},
	{"edit", "Edit — mutate / execute"},
	{"verify", "Verify — check / validate"},
	{"meta", "Meta — routing"},
	{"cross", "Cross — phase-agnostic utilities"},
}

// contractsRiskOrder is the canonical risk-level order for the at-a-glance
// table.
var contractsRiskOrder = []string{"low", "medium", "high", "critical"}

// contractsExamples is the hand-written JSON-RPC usage appendix. The
// generator preserves it verbatim so regeneration never loses it.
const contractsExamples = `## Usage examples

### Example 1 — explore: understand a symbol (` + "`kern_graph`" + `)

` + "```json" + `
{"jsonrpc":"2.0","id":1,"method":"tools/call","params":{"name":"kern_graph","arguments":{"symbol":"User.Login","root":"/path/to/project"}}}
` + "```" + `

### Example 2 — plan: simulate an impact (` + "`kern_impact`" + `)

` + "```json" + `
{"jsonrpc":"2.0","id":2,"method":"tools/call","params":{"name":"kern_impact","arguments":{"change":"rename Widget to Gadget","root":"/path/to/project"}}}
` + "```" + `

### Example 3 — edit: run a command safely (` + "`kern_sandbox`" + `)

` + "```json" + `
{"jsonrpc":"2.0","id":3,"method":"tools/call","params":{"name":"kern_sandbox","arguments":{"root":"/path/to/project","command":"make migrate","timeout":"121"}}}
` + "```" + `

### Example 4 — verify: check an agent's output for hallucinations (` + "`kern_verify_output`" + `)

` + "```json" + `
{"jsonrpc":"2.0","id":4,"method":"tools/call","params":{"name":"kern_verify_output","arguments":{"text":"The fix lives in internal/mcp/server.go, function Serve."}}}
` + "```" + `

### Example 5 — meta: route by intent (` + "`kern_meta`" + `)

` + "```json" + `
{"jsonrpc":"2.0","id":5,"method":"tools/call","params":{"name":"kern_meta","arguments":{"request":"how does dispatch work?","root":"/path/to/project"}}}
` + "```" + `
`

// GenerateContractsDoc renders the MCP tool contracts as a deterministic
// markdown document: an at-a-glance summary, a catalog table, and one
// detailed contract per tool (grouped by phase), plus the preserved usage
// examples. The output is byte-stable for a given catalog, so staleness is a
// content-hash compare — the same contract as the tool catalog (G36).
func GenerateContractsDoc(catalog []ToolInfo) []byte {
	sorted := append([]ToolInfo(nil), catalog...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Name < sorted[j].Name })

	phaseCounts := map[string]int{}
	riskCounts := map[string]int{}
	for _, t := range catalog {
		phaseCounts[t.Phase]++
		riskCounts[t.RiskLevel]++
	}

	var b bytes.Buffer
	b.WriteString("<!-- Generated by `kern gen-contracts` — do not edit by hand.\n")
	b.WriteString("     Run `kern gen-contracts` after adding, renaming, or changing an MCP tool.\n")
	b.WriteString("     The contracts:doc gate fails when this file is stale or a tool is missing. -->\n")
	b.WriteString("# Kern MCP Tool Contracts\n\n")
	b.WriteString("> **Source of truth:** `internal/mcp/catalog/tools.go` — the tool registration table. This document is generated from that table; if the two disagree, the table wins.\n\n")
	b.WriteString("This page is the authoritative reference for every tool the kern MCP server exposes. Each contract lists the tool's name, agent phase, risk level, description, input parameters and required parameters.\n\n")

	// D6: the argument-coercion contract shared by every tool. Kept inside the
	// generator so `kern gen-contracts` (and the byte-identical contracts:doc
	// gate) carries it — a hand-edited doc would be wiped on the next
	// regeneration.
	b.WriteString("## Argument coercion\n\n")
	b.WriteString("Every scalar argument whose schema declares `type: \"string\"` follows a documented coercion contract. The server accepts:\n\n")
	b.WriteString("| Input value | Result |\n|---|---|\n")
	b.WriteString("| JSON string | used verbatim (trimmed) |\n")
	b.WriteString("| JSON number | coerced to its canonical string form (e.g. `query: 12345` becomes `\"12345\"`) |\n")
	b.WriteString("| JSON boolean | coerced (`true`/`false`) for the boolean-style string flags such as `semantic`, `force`, `apply` |\n\n")
	b.WriteString("The server rejects **null**, **object** and **array** values for string-typed arguments with a tool error (`isError: true`) naming the argument, the tool and the expected type — for example `query: {}` on `kern_search` fails instead of silently yielding \"no symbols matched\". Arguments not declared in a tool's schema (e.g. `max_output`, `agent_id`) and non-string-typed parameters (`integer`, `boolean`, `object`, `array`) are not coerced by this rule; they are read by their own lenient helpers (`atoiArg`, `argBool`, `argStrings`), which already fail loud on malformed values. Numeric arguments keep their lenient parsing (string or number) and any bounds the handler already enforces.\n\n")

	// Catalog at a glance.
	b.WriteString("## Catalog at a glance\n\n")
	b.WriteString("| Metric | Value |\n|---|---|\n")
	fmt.Fprintf(&b, "| Total tools | %d |\n", len(sorted))
	var phaseParts []string
	for _, p := range contractPhases {
		phaseParts = append(phaseParts, fmt.Sprintf("%s (%d)", p.name, phaseCounts[p.name]))
	}
	fmt.Fprintf(&b, "| Phases | %s |\n", strings.Join(phaseParts, ", "))
	var riskParts []string
	for _, r := range contractsRiskOrder {
		riskParts = append(riskParts, fmt.Sprintf("%s (%d)", r, riskCounts[r]))
	}
	fmt.Fprintf(&b, "| Risk levels | %s |\n\n", strings.Join(riskParts, ", "))

	// Full catalog summary.
	b.WriteString("## Full catalog (summary)\n\n")
	b.WriteString("| Tool | Phase | Risk | Description |\n|---|---|---|---|\n")
	for _, t := range sorted {
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s |\n", t.Name, t.Phase, t.RiskLevel, strings.ReplaceAll(t.Description, "\n", " "))
	}

	// Detailed contracts, grouped by phase.
	b.WriteString("\n## Detailed contracts\n\n")
	for _, p := range contractPhases {
		b.WriteString("## " + p.label + "\n\n")
		for _, t := range sorted {
			if t.Phase == p.name {
				renderContract(&b, t)
			}
		}
	}

	b.WriteString(contractsExamples)
	b.WriteString("\n")
	return b.Bytes()
}

// renderContract writes one detailed tool contract section.
func renderContract(b *bytes.Buffer, t ToolInfo) {
	fmt.Fprintf(b, "### `%s`\n\n", t.Name)
	fmt.Fprintf(b, "- **Phase:** %s\n", t.Phase)
	fmt.Fprintf(b, "- **Risk level:** %s\n", t.RiskLevel)
	required := contractRequiredKeys(t.InputSchema)
	if len(required) > 0 {
		fmt.Fprintf(b, "- **Required:** `%s`\n\n", strings.Join(required, "`, `"))
	} else {
		b.WriteString("- **Required:** none\n\n")
	}
	b.WriteString(strings.ReplaceAll(t.Description, "\n", " ") + "\n\n")
	props := contractProperties(t.InputSchema)
	if len(props) == 0 {
		b.WriteString("_No input parameters._\n\n")
		return
	}
	b.WriteString("| Parameter | Type | Required | Description |\n|---|---|---|---|\n")
	for _, p := range props {
		req := "no"
		if p.required {
			req = "yes"
		}
		fmt.Fprintf(b, "| `%s` | %s | %s | %s |\n", p.name, p.typ, req, strings.ReplaceAll(p.desc, "\n", " "))
	}
	b.WriteString("\n")
}

// contractProperty is one rendered input-schema property.
type contractProperty struct {
	name     string
	typ      string
	desc     string
	required bool
}

// contractRequiredKeys returns the schema's required property names (sorted).
func contractRequiredKeys(schema map[string]any) []string {
	raw, ok := schema["required"].([]any)
	if !ok {
		return nil
	}
	var out []string
	for _, r := range raw {
		if s, ok := r.(string); ok {
			out = append(out, s)
		}
	}
	sort.Strings(out)
	return out
}

// contractProperties renders the schema's properties as a sorted table.
func contractProperties(schema map[string]any) []contractProperty {
	props, ok := schema["properties"].(map[string]any)
	if !ok {
		return nil
	}
	required := map[string]bool{}
	for _, r := range contractRequiredKeys(schema) {
		required[r] = true
	}
	names := slices.Sorted(maps.Keys(props))
	var out []contractProperty
	for _, name := range names {
		p, _ := props[name].(map[string]any)
		typ, _ := p["type"].(string)
		desc, _ := p["description"].(string)
		out = append(out, contractProperty{name: name, typ: typ, desc: desc, required: required[name]})
	}
	return out
}

// ContractsDocCheck verifies the committed docs/mcp/tool-contracts.md is
// present, covers every registered MCP tool, and is byte-identical to a
// fresh generation — the same drift guard as catalog:doc (G36), for the
// contracts document. It BLOCKs on any violation.
type ContractsDocCheck struct {
	root  string
	tools []ToolInfo
}

// NewContractsDocCheck constructs the contracts-doc check bound to a repo
// root. tools is the injected live MCP catalog — mandatory (a wiring site
// that omits it fails to compile; an empty list fails loud at Run).
func NewContractsDocCheck(root string, tools []ToolInfo) *ContractsDocCheck {
	return &ContractsDocCheck{root: root, tools: tools}
}

// WriteContractsDoc regenerates docs/mcp/tool-contracts.md from the live MCP
// catalog and returns the written path. Errors when no catalog is injected.
func WriteContractsDoc(root string, tools []ToolInfo) (string, error) {
	if err := requireCatalogTools(tools); err != nil {
		return "", err
	}
	docPath := filepath.Join(root, filepath.FromSlash(contractsDocRelPath))
	if err := os.MkdirAll(filepath.Dir(docPath), 0o755); err != nil {
		return "", err
	}
	if err := os.WriteFile(docPath, GenerateContractsDoc(tools), 0o644); err != nil {
		return "", err
	}
	return docPath, nil
}

// Name is the stable check identifier.
func (c *ContractsDocCheck) Name() string { return "contracts:doc" }

// Run compares the committed contracts doc against the live MCP catalog.
func (c *ContractsDocCheck) Run(ctx context.Context, req domain.ChangeRequest) (domain.CheckResult, error) {
	if c.root == "" {
		return domain.CheckResult{Name: c.Name(), Status: domain.StatusError, Error: "repository root required"}, nil
	}
	if err := requireCatalogTools(c.tools); err != nil {
		return domain.CheckResult{Name: c.Name(), Status: domain.StatusError, Error: err.Error()}, nil
	}
	docPath := filepath.Join(c.root, filepath.FromSlash(contractsDocRelPath))
	committed, err := os.ReadFile(docPath)
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return domain.CheckResult{Name: c.Name(), Status: domain.StatusBlock, Error: fmt.Sprintf("generated tool contracts missing at %s — run `kern gen-contracts`", contractsDocRelPath)}, nil
		}
		return domain.CheckResult{Name: c.Name(), Status: domain.StatusError, Error: fmt.Sprintf("read %s: %v", docPath, err)}, nil
	}

	docText := string(committed)
	var missing []string
	for _, t := range c.tools {
		if !strings.Contains(docText, "`"+t.Name+"`") {
			missing = append(missing, t.Name)
		}
	}
	if len(missing) > 0 {
		return domain.CheckResult{Name: c.Name(), Status: domain.StatusBlock, Error: fmt.Sprintf("docs/mcp/tool-contracts.md does not document registered tool(s): %s — run `kern gen-contracts`", strings.Join(missing, ", "))}, nil
	}
	fresh := GenerateContractsDoc(c.tools)
	if !bytes.Equal(committed, fresh) {
		return domain.CheckResult{Name: c.Name(), Status: domain.StatusBlock, Error: "docs/mcp/tool-contracts.md is stale or out of order — run `kern gen-contracts` and commit the regenerated file"}, nil
	}
	return domain.CheckResult{Name: c.Name(), Status: domain.StatusPass}, nil
}
