package main

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/JayveerPrajapati/kern/internal/heal"
	"github.com/JayveerPrajapati/kern/internal/llm"
)

func main() {
	fmt.Println("=================================================================")
	fmt.Println("🚀 KERN LIVE DEMO: Deterministic Engine + Host Model Delegation")
	fmt.Println("=================================================================")
	fmt.Println()

	// 1. Check active provider detection before registering host sampler
	fmt.Println("[Step 1] Inspecting LLM Provider Chain (before host registration)...")
	p1, _ := llm.NewProvider()
	fmt.Printf("   Active provider: %T\n", p1)
	fmt.Printf("   HasHostSampler:  %v\n\n", llm.HasHostSampler())

	// 2. Connect the Host Agent Sampler (simulating Antigravity / Gemini 3.7 active session)
	fmt.Println("[Step 2] Registering Host Agent Model via MCP Sampling...")
	disposer := llm.RegisterHostSampler(func(ctx context.Context, system, user string, opts llm.Options) (string, error) {
		fmt.Println("   --> [Host Model Intercept] Received prompt from Kern engine.")
		fmt.Println("   --> [Host Model Intercept] Analyzing compilation diagnostics and synthesizing fix...")

		// Simulate the host model returning the corrected full-file block
		fixedCode := `package main

import "fmt"

func CalculateDiscount(price float64, rate float64) float64 {
	return price * (1.0 - rate)
}

func main() {
	finalPrice := CalculateDiscount(100.0, 0.20)
	fmt.Printf("Final price: $%.2f\n", finalPrice)
}
`
		return fmt.Sprintf("### FILE: main.go\n%s", fixedCode), nil
	})
	defer disposer()

	fmt.Printf("   HasHostSampler:  %v (Active Host Agent attached!)\n\n", llm.HasHostSampler())

	// 3. Inspect provider chain after host registration
	fmt.Println("[Step 3] Checking Provider Factory Auto-Chain...")
	p2, err := llm.NewProvider()
	if err != nil {
		panic(err)
	}
	fmt.Printf("   Active provider resolved: %T\n", p2)
	fmt.Printf("   Is Remote/Mask Required?: %v (False = Safe local host session)\n\n", llm.MaskRequired())

	// 4. Set up a broken project in a temporary workspace
	fmt.Println("[Step 4] Setting up a project with deliberate compilation error...")
	tmpDir, err := os.MkdirTemp("", "kern-demo-*")
	if err != nil {
		panic(err)
	}
	defer func() { _ = os.RemoveAll(tmpDir) }()

	brokenCode := `package main

import "fmt"

// Bug: Type mismatch: returning string instead of float64
func CalculateDiscount(price float64, rate float64) float64 {
	return "invalid string return"
}

func main() {
	finalPrice := CalculateDiscount(100.0, 0.20)
	fmt.Printf("Final price: $%.2f\n", finalPrice)
}
`
	goMod := `module demo

go 1.25
`
	_ = os.WriteFile(filepath.Join(tmpDir, "main.go"), []byte(brokenCode), 0o644)
	_ = os.WriteFile(filepath.Join(tmpDir, "go.mod"), []byte(goMod), 0o644)
	fmt.Println("   Created temporary project with syntax/type error at:", tmpDir)

	// 5. Run Kern Self-Healing (`heal.Run`)
	fmt.Println("\n[Step 5] Executing `kern heal` Self-Repair Loop...")
	fmt.Println("   - Tier 1 (Kern Core): Compiles project, isolates diagnostics locally (0 tokens)")
	fmt.Println("   - Tier 2 (Host Agent): Synthesizes fix via registered MCP sampling")
	fmt.Println("   - Verification: Runs validation in sandbox worktree and checks diff")
	fmt.Println("   -----------------------------------------------------------------")

	start := time.Now()
	res := heal.Run(context.Background(), tmpDir, "Fix type mismatch in CalculateDiscount", "", 3, 30*time.Second, true)

	fmt.Println("\n[Step 6] Execution Results:")
	fmt.Printf("   Validated Cleanly: %v\n", res.Validated)
	fmt.Printf("   Iterations:        %d round(s)\n", res.Iterations)
	fmt.Printf("   Duration:          %v\n", time.Since(start).Round(time.Millisecond))
	fmt.Printf("   Changed Files:     %s\n", strings.Join(res.Changes, ", "))

	if res.Diff != "" {
		fmt.Println("\n[Step 7] Unified Diff Generated by Kern:")
		fmt.Println("-----------------------------------------------------------------")
		fmt.Println(res.Diff)
		fmt.Println("-----------------------------------------------------------------")
	}

	fmt.Println("🎉 DEMO COMPLETE: Zero Ollama daemons needed — Host frontier intelligence utilized seamlessly!")
}
