package setup

import (
	"embed"
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

//go:embed assets/plugin/kern.ts
var pluginFS embed.FS

//go:embed assets/AGENTS.md
var rulesFS embed.FS

// Status reports one agent's wiring state.
type Status struct {
	Agent     string
	Installed bool
	Path      string
	Note      string
}

// detectedAgent maps each agent identifier to a detection function.
// An agent is considered "present" when any of its indicators exist.
type agentDetector struct {
	agent  string
	paths  []string // project-relative or home-relative paths to check
	binary string   // optional: binary name to look for on PATH
}

// agentDetectors is the registry of all supported agents for auto-detection.
var agentDetectors = []agentDetector{
	{agent: "opencode", paths: []string{"opencode.json"}, binary: "opencode"},
	{agent: "claude", paths: []string{"CLAUDE.md", ".claude/settings.json"}, binary: "claude"},
	{agent: "cursor", paths: []string{".cursor/mcp.json", ".cursor/rules"}, binary: "cursor"},
	{agent: "copilot", paths: []string{".vscode/mcp.json", ".github/copilot-instructions.md"}, binary: ""},
	{agent: "gemini", paths: []string{"GEMINI.md", ".gemini/settings.json"}, binary: ""},
	{agent: "codex", paths: []string{".codex/config.toml"}, binary: "codex"},
	{agent: "continue", paths: []string{".continuerc.json"}, binary: ""},
	{agent: "windsurf", paths: []string{".windsurfrc", ".codeium/windsurf/mcp_config.json"}, binary: ""},
	{agent: "zed", paths: []string{"~/.config/zed/settings.json"}, binary: ""},
	{agent: "qwen", paths: []string{"~/.qwen/settings.json"}, binary: ""},
	{agent: "qoder", paths: []string{"~/.qoder/mcp.json"}, binary: ""},
	{agent: "kiro", paths: []string{".kiro/settings/mcp.json"}, binary: ""},
}

// instructionFiles maps each agent to its project-level instruction file
// that receives the kern-first policy. These files are git-ignored when
// generated by setup (they carry machine-specific paths or are redundant
// with the universal AGENTS.md).
var instructionFiles = map[string]string{
	"claude":  "CLAUDE.md",
	"gemini":  "GEMINI.md",
	"copilot": ".github/copilot-instructions.md",
	"cursor":  ".cursor/instructions/kern.mdc",
}

// DetectAgents scans the project root and system PATH for evidence that each
// known agent is in use. Returns the list of detected agent names.
func DetectAgents(root string) []string {
	var detected []string
	for _, d := range agentDetectors {
		if isAgentPresent(root, d) {
			detected = append(detected, d.agent)
		}
	}
	return detected
}

func isAgentPresent(root string, d agentDetector) bool {
	for _, p := range d.paths {
		path := p
		if strings.HasPrefix(p, "~") {
			path = homeJoin(strings.TrimPrefix(p, "~"))
		} else {
			path = filepath.Join(root, p)
		}
		if _, err := os.Stat(path); err == nil {
			return true
		}
	}
	if d.binary != "" {
		if _, err := exec.LookPath(d.binary); err == nil {
			return true
		}
	}
	return false
}

// wireInstructions writes the kern-first policy block into each detected
// agent's instruction file, creating the file if missing. Each written
// file receives an idempotency marker so re-running setup doesn't duplicate.
func wireInstructions(root string, agents []string) []Status {
	rules, err := rulesFS.ReadFile("assets/AGENTS.md")
	if err != nil {
		return []Status{{Agent: "instructions", Note: err.Error()}}
	}
	rulesText := string(rules)
	var out []Status
	for _, agent := range agents {
		file, ok := instructionFiles[agent]
		if !ok {
			continue
		}
		path := filepath.Join(root, file)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			out = append(out, Status{Agent: agent + "-instruction", Note: err.Error()})
			continue
		}
		status := writeInstructionFile(path, rulesText)
		status.Agent = agent + "-instruction"
		out = append(out, status)
	}
	return out
}

// writePerm returns the permission bits to use when writing a config-like
// file. Existing files keep their current permissions (configs with tokens are
// often 0600 and must not be widened); new files default to 0600.
func writePerm(path string) os.FileMode {
	if info, err := os.Stat(path); err == nil {
		return info.Mode().Perm()
	}
	return 0o600
}

// writeInstructionFile writes the kern-first policy block to a single
// instruction file, idempotently (never duplicates the block).
func writeInstructionFile(path, rulesText string) Status {
	marker := "<!-- kern-instruction: managed by kern setup; remove marker to stop managing -->"
	content, _ := os.ReadFile(path)
	cur := string(content)
	if strings.Contains(cur, "kern-instruction:") || strings.Contains(cur, "kern usage rules") {
		return Status{Agent: "", Installed: true, Path: path, Note: "kern-first policy already present"}
	}
	var joined string
	if strings.TrimSpace(cur) == "" {
		joined = marker + "\n\n" + rulesText
	} else {
		joined = strings.TrimRight(cur, "\n") + "\n\n" + marker + "\n\n" + rulesText
	}
	if err := os.WriteFile(path, []byte(joined), writePerm(path)); err != nil {
		return Status{Agent: "", Path: path, Note: err.Error()}
	}
	return Status{Agent: "", Installed: true, Path: path, Note: "kern-first policy written"}
}

// wireRulesFile appends the embedded kern rules block to a single rule file,
// idempotently (never duplicates) and never overwriting existing content.
func wireRulesFile(root, name string) Status {
	path := filepath.Join(root, name)
	content := ""
	if b, err := os.ReadFile(path); err == nil {
		content = string(b)
	}
	if strings.Contains(content, "kern usage rules") {
		return Status{Agent: name, Installed: true, Path: path, Note: "rules already present"}
	}
	rules, err := rulesFS.ReadFile("assets/AGENTS.md")
	if err != nil {
		return Status{Agent: name, Path: path, Note: err.Error()}
	}
	var joined string
	if content == "" {
		joined = string(rules)
	} else {
		joined = strings.TrimRight(content, "\n") + "\n\n" + string(rules)
	}
	if err := os.WriteFile(path, []byte(joined), writePerm(path)); err != nil {
		return Status{Agent: name, Path: path, Note: err.Error()}
	}
	return Status{Agent: name, Installed: true, Path: path, Note: "rules appended"}
}

// gitignoreMarker identifies the block of generated entries this package owns.
const gitignoreMarker = "# --- kern generated (agent wiring, machine-specific) ---"

// gitignoreGenerated appends the setup-generated project files to .gitignore.
// Machine-specific configs (absolute binary paths in .mcp.json, .claude/,
// .cursor/, .kiro/ hooks) must never be committed; uncommitted copies would
// leak the machine layout and stale paths. But portable configs like
// opencode.json (relative "bin/kern-mcp" command) and the .opencache plugins
// directory ARE committed — only their machine-specific subdirs (node_modules)
// are ignored.
// Idempotent: the block is added once, and only when absent.
func gitignoreGenerated(root string) Status {
	path := filepath.Join(root, ".gitignore")
	data, err := os.ReadFile(path)
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return Status{Agent: "gitignore", Path: path, Note: err.Error()}
	}
	if strings.Contains(string(data), gitignoreMarker) {
		return Status{Agent: "gitignore", Installed: true, Path: path, Note: "generated entries already gitignored"}
	}
	block := "\n" + gitignoreMarker + `
# Re-run ` + "`kern setup`" + ` to refresh. Unignore a line to commit shared config.
.mcp.json
.claude/
.cursor/
.gemini/
.kiro/
.kern/
.opencode/node_modules/
.opencode/package-lock.json
CLAUDE.md
GEMINI.md
.github/copilot-instructions.md
`
	out := strings.TrimRight(string(data), "\n")
	if out != "" {
		out += "\n"
	}
	out += block
	if err := os.WriteFile(path, []byte(out), 0o644); err != nil {
		return Status{Agent: "gitignore", Path: path, Note: err.Error()}
	}
	return Status{Agent: "gitignore", Installed: true, Path: path, Note: "generated entries added to .gitignore"}
}
