package setup

import (
	"os"
	"path/filepath"
	"strings"
)

// wireCursorRules writes an instruction rule for Cursor. Cursor's rule events
// cannot execute commands, so the rule tells the model to use kern's MCP tools
// (compression + memory) — the only interception Cursor's platform supports.
func wireCursorRules(root string) Status {
	path := filepath.Join(root, ".cursor", "rules", "kern-hooks.mdc")
	if b, err := os.ReadFile(path); err == nil && strings.Contains(string(b), "kern-hooks: generated by kern setup") {
		return Status{Agent: "cursor-rules", Installed: true, Path: path, Note: "cursor rule already present"}
	}
	content := `---
description: Use kern to compress large outputs and keep session memory
globs:
alwaysApply: false
---
<!-- kern-hooks: generated by kern setup; remove this marker to stop managing the file -->

- When a tool output is very large (roughly more than 4000 characters), do not
  paste it raw into context. Run ` + "`kern_optimize_log`" + ` (or ` + "`kern_context_budget`" + `) on it and
  work from the compressed summary.
- After editing files, record what changed with ` + "`kern_memory_add`" + ` (e.g. "Edited <path>").
- When a command fails, record the failure line with ` + "`kern_memory_add`" + ` so a
  compacted or fresh session can recover the state.
`
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return Status{Agent: "cursor-rules", Path: path, Note: err.Error()}
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return Status{Agent: "cursor-rules", Path: path, Note: err.Error()}
	}
	return Status{Agent: "cursor-rules", Installed: true, Path: path, Note: "cursor kern rule written"}
}
