package setup

import (
	"embed"
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

//go:embed assets/plugin/kern.ts
var pluginFS embed.FS

//go:embed assets/AGENTS.md
var rulesFS embed.FS

// Status reports one agent's wiring state.
type Status struct {
	Agent     string
	Installed bool
	// Skipped marks a deliberate no-op (agent not installed, config dir
	// absent). It is not an error: setup must not exit non-zero for skips,
	// only for real failures.
	Skipped bool
	Path    string
	Note    string
}

// detectedAgent maps each agent identifier to a detection function.
// An agent is considered "present" when any of its indicators exist.
type agentDetector struct {
	agent  string
	paths  []string // project-relative or home-relative paths to check
	binary string   // optional: binary name to look for on PATH
}

// agentDetectors is the registry of all supported agents for auto-detection.
var agentDetectors = []agentDetector{
	{agent: "opencode", paths: []string{"opencode.json"}, binary: "opencode"},
	{agent: "claude", paths: []string{"CLAUDE.md", ".claude/settings.json"}, binary: "claude"},
	{agent: "cursor", paths: []string{".cursor/mcp.json", ".cursor/rules"}, binary: "cursor"},
	{agent: "copilot", paths: []string{".vscode/mcp.json", ".github/copilot-instructions.md"}, binary: ""},
	{agent: "gemini", paths: []string{"GEMINI.md", ".gemini/settings.json"}, binary: ""},
	{agent: "codex", paths: []string{".codex/config.toml"}, binary: "codex"},
	{agent: "continue", paths: []string{".continuerc.json"}, binary: ""},
	{agent: "windsurf", paths: []string{".windsurfrc", ".codeium/windsurf/mcp_config.json"}, binary: ""},
	{agent: "zed", paths: []string{"~/.config/zed/settings.json"}, binary: ""},
	{agent: "qwen", paths: []string{"~/.qwen/settings.json"}, binary: ""},
	{agent: "qoder", paths: []string{"~/.qoder/mcp.json"}, binary: ""},
	{agent: "kiro", paths: []string{".kiro/settings/mcp.json"}, binary: ""},
}

// instructionFiles maps each agent to its project-level instruction file
// that receives the kern-first policy. These files are git-ignored when
// generated by setup (they carry machine-specific paths or are redundant
// with the universal AGENTS.md).
var instructionFiles = map[string]string{
	"claude":  "CLAUDE.md",
	"gemini":  "GEMINI.md",
	"copilot": ".github/copilot-instructions.md",
	"cursor":  ".cursor/instructions/kern.mdc",
}

// DetectAgents scans the project root and system PATH for evidence that each
// known agent is in use. Returns the list of detected agent names.
func DetectAgents(root string) []string {
	var detected []string
	for _, d := range agentDetectors {
		if isAgentPresent(root, d) {
			detected = append(detected, d.agent)
		}
	}
	return detected
}

func isAgentPresent(root string, d agentDetector) bool {
	for _, p := range d.paths {
		path := p
		if strings.HasPrefix(p, "~") {
			path = homeJoin(strings.TrimPrefix(p, "~"))
		} else {
			path = filepath.Join(root, p)
		}
		if _, err := os.Stat(path); err == nil {
			return true
		}
	}
	if d.binary != "" {
		if _, err := exec.LookPath(d.binary); err == nil {
			return true
		}
	}
	return false
}

// wireInstructions writes the kern-first policy block into each detected
// agent's instruction file, creating the file if missing. Each written
// file receives an idempotency marker so re-running setup doesn't duplicate.
func wireInstructions(root string, agents []string) []Status {
	rules, err := rulesFS.ReadFile("assets/AGENTS.md")
	if err != nil {
		return []Status{{Agent: "instructions", Note: err.Error()}}
	}
	rulesText := string(rules)
	var out []Status
	for _, agent := range agents {
		file, ok := instructionFiles[agent]
		if !ok {
			continue
		}
		path := filepath.Join(root, file)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			out = append(out, Status{Agent: agent + "-instruction", Note: err.Error()})
			continue
		}
		status := writeInstructionFile(path, rulesText)
		status.Agent = agent + "-instruction"
		out = append(out, status)
	}
	return out
}

// writePerm returns the permission bits to use when writing a config-like
// file. Existing files keep their current permissions (configs with tokens are
// often 0600 and must not be widened); new files default to 0600.
func writePerm(path string) os.FileMode {
	if info, err := os.Stat(path); err == nil {
		return info.Mode().Perm()
	}
	return 0o600
}

// instructionMarkerOpen / instructionMarkerClose bracket the kern-managed block
// in a per-agent instruction file (CLAUDE.md, GEMINI.md, etc.). They let us
// remove-and-rewrite the block on every setup run so an upgrade always writes
// fresh rules rather than skipping when stale rules are detected.
const (
	instructionMarkerOpen  = "<!-- kern-instruction: managed by kern setup; do not edit between markers -->"
	instructionMarkerClose = "<!-- /kern-instruction -->"
)

// writeInstructionFile writes the kern-first policy block to a single
// instruction file. On every run it removes any existing kern-managed block
// (between instructionMarkerOpen and instructionMarkerClose) and re-inserts
// the fresh embedded rules, preserving all user content outside the block.
// This is overwrite-always: an upgrade with new rules always replaces the old
// block rather than skipping when a marker is present.
// The same per-agent files (CLAUDE.md, GEMINI.md, …) can also be written by
// wireRulesFile using an unmarked kern section. To avoid duplicate blocks when
// both paths run, writeInstructionFile strips BOTH the marked instruction
// block AND any unmarked kern section before re-inserting.
func writeInstructionFile(path, rulesText string) Status {
	cur, _ := os.ReadFile(path)
	content := string(cur)
	cleaned := removeMarkedBlock(content, instructionMarkerOpen, instructionMarkerClose)
	cleaned = removeKernSection(cleaned)
	block := instructionMarkerOpen + "\n\n" + strings.TrimRight(rulesText, "\n") + "\n\n" + instructionMarkerClose
	var joined string
	if strings.TrimSpace(cleaned) == "" {
		joined = block + "\n"
	} else {
		joined = strings.TrimRight(cleaned, "\n") + "\n\n" + block + "\n"
	}
	if err := os.WriteFile(path, []byte(joined), writePerm(path)); err != nil {
		return Status{Agent: "", Path: path, Note: err.Error()}
	}
	return Status{Agent: "", Installed: true, Path: path, Note: "kern-first policy written"}
}

// removeMarkedBlock strips the substring between openMarker and closeMarker
// (inclusive of both markers) from s. If either marker is absent the input is
// returned unchanged. Used to refresh kern-managed blocks on every setup run.
func removeMarkedBlock(s, openMarker, closeMarker string) string {
	start := strings.Index(s, openMarker)
	if start < 0 {
		return s
	}
	end := strings.Index(s[start:], closeMarker)
	if end < 0 {
		return s
	}
	end += start + len(closeMarker)
	// Collapse a single trailing newline so we don't accumulate blank lines
	// across rewrites.
	if end < len(s) && s[end] == '\n' {
		end++
	}
	return s[:start] + s[end:]
}

// wireRulesFile writes the embedded kern rules block to a single rule file
// (AGENTS.md). On every run it removes any existing kern section and re-inserts
// the fresh embedded rules, preserving all user content outside the block.
// This is overwrite-always: an upgrade with new rules always replaces the old
// block rather than skipping when a "kern usage rules" header is present.
// The same per-agent files (CLAUDE.md, GEMINI.md, …) can also be written by
// writeInstructionFile using a marked block (instructionMarkerOpen/Close).
// To avoid duplicate blocks when both paths run, wireRulesFile strips BOTH the
// unmarked kern section AND any marked instruction block before re-inserting.
func wireRulesFile(root, name string) Status {
	path := filepath.Join(root, name)
	content := ""
	if b, err := os.ReadFile(path); err == nil {
		content = string(b)
	}
	rules, err := rulesFS.ReadFile("assets/AGENTS.md")
	if err != nil {
		return Status{Agent: name, Path: path, Note: err.Error()}
	}
	cleaned := removeMarkedBlock(content, instructionMarkerOpen, instructionMarkerClose)
	cleaned = removeKernSection(cleaned)
	// If the block is unchanged (same content after remove+reinsert), skip the
	// write to avoid needlessly bumping mtime. This mirrors the global path.
	final := mergeAppend(cleaned, string(rules))
	if content != "" && final == content {
		return Status{Agent: name, Installed: true, Path: path, Note: "rules already current"}
	}
	if err := os.WriteFile(path, []byte(final), writePerm(path)); err != nil {
		return Status{Agent: name, Path: path, Note: err.Error()}
	}
	return Status{Agent: name, Installed: true, Path: path, Note: "rules written"}
}

// gitignoreMarker identifies the block of generated entries this package owns.
const gitignoreMarker = "# --- kern generated (agent wiring, machine-specific) ---"

// gitignoreGenerated writes the setup-generated project files to .gitignore.
// Machine-specific configs (absolute binary paths in .mcp.json, .claude/,
// .cursor/, .kiro/ hooks) must never be committed; uncommitted copies would
// leak the machine layout and stale paths. But portable configs like
// opencode.json (relative "bin/kern-mcp" command) and the .opencache plugins
// directory ARE committed — only their machine-specific subdirs (node_modules)
// are ignored.
// Overwrite-always: on every run the existing kern-generated block (between the
// markers) is removed and the fresh block re-inserted, so new ignore entries
// added in an upgrade are picked up rather than skipped.
func gitignoreGenerated(root string) Status {
	path := filepath.Join(root, ".gitignore")
	data, err := os.ReadFile(path)
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return Status{Agent: "gitignore", Path: path, Note: err.Error()}
	}
	closeMarker := "# --- end kern generated ---"
	block := "\n" + gitignoreMarker + `
# Re-run ` + "`kern setup`" + ` to refresh. Unignore a line to commit shared config.
.mcp.json
.claude/
.cursor/
.gemini/
.kiro/
.kern/
.continue/
.windsurf/
.opencode/node_modules/
.opencode/package-lock.json
.cortexkit/
CLAUDE.md
GEMINI.md
.github/copilot-instructions.md
.github/hooks/
` + closeMarker + "\n"
	cleaned := removeMarkedBlock(string(data), gitignoreMarker, closeMarker)
	out := strings.TrimRight(cleaned, "\n")
	if out != "" {
		out += "\n"
	}
	out += block
	if err := os.WriteFile(path, []byte(out), 0o644); err != nil {
		return Status{Agent: "gitignore", Path: path, Note: err.Error()}
	}
	return Status{Agent: "gitignore", Installed: true, Path: path, Note: "generated entries written to .gitignore"}
}
