// Package graph builds and renders architectural boundary visual graphs from
// .kern/boundaries.json for human inspection and documentation.
package graph

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// BoundaryRule represents a single boundary edge between two components.
type BoundaryRule struct {
	From   string `json:"from"`
	To     string `json:"to"`
	Action string `json:"action"` // "forbid" | "allow"
	Reason string `json:"reason,omitempty"`
}

// Payload mirrors the schema of .kern/boundaries.json.
type Payload struct {
	Rules []BoundaryRule `json:"rules"`
}

// Graph models the architectural boundary graph.
type Graph struct {
	RepoRoot string         `json:"repo_root"`
	Nodes    []string       `json:"nodes"`
	Rules    []BoundaryRule `json:"rules"`
}

// Load loads and parses .kern/boundaries.json from the given repository root.
func Load(repoRoot string) (*Graph, error) {
	path := filepath.Join(repoRoot, ".kern", "boundaries.json")
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return &Graph{
				RepoRoot: repoRoot,
				Nodes:    nil,
				Rules:    nil,
			}, nil
		}
		return nil, fmt.Errorf("read boundaries: %w", err)
	}

	var p Payload
	if err := json.Unmarshal(data, &p); err != nil {
		return nil, fmt.Errorf("parse boundaries.json: %w", err)
	}

	nodeSet := make(map[string]bool)
	for _, r := range p.Rules {
		if r.From != "" {
			nodeSet[r.From] = true
		}
		if r.To != "" {
			nodeSet[r.To] = true
		}
	}

	nodes := make([]string, 0, len(nodeSet))
	for n := range nodeSet {
		nodes = append(nodes, n)
	}
	sort.Strings(nodes)

	return &Graph{
		RepoRoot: repoRoot,
		Nodes:    nodes,
		Rules:    p.Rules,
	}, nil
}

// ToMermaid generates a Mermaid flowchart (LR direction) visualizing the architecture rules.
// Forbidden edges are styled as dotted red arrows; allowed edges as solid blue arrows.
func (g *Graph) ToMermaid() string {
	var sb strings.Builder
	sb.WriteString("flowchart LR\n")
	sb.WriteString("  %% Architectural Boundary Graph generated by Blueprint\n")

	if len(g.Rules) == 0 {
		sb.WriteString("  Empty[\"No boundary rules declared in .kern/boundaries.json\"]\n")
		return sb.String()
	}

	// Declare and sanitize nodes
	for _, node := range g.Nodes {
		id := sanitizeID(node)
		sb.WriteString(fmt.Sprintf("  %s[\"%s\"]\n", id, node))
	}

	sb.WriteString("\n")

	// Render edges with actions
	for _, r := range g.Rules {
		fromID := sanitizeID(r.From)
		toID := sanitizeID(r.To)
		action := strings.ToLower(r.Action)

		label := r.Action
		if r.Reason != "" {
			label = fmt.Sprintf("%s: %s", r.Action, r.Reason)
		}

		if action == "forbid" {
			// Dotted arrow with cross/forbid note
			sb.WriteString(fmt.Sprintf("  %s -. \"❌ %s\" .-> %s\n", fromID, label, toID))
		} else {
			// Solid arrow
			sb.WriteString(fmt.Sprintf("  %s -->|✓ %s| %s\n", fromID, label, toID))
		}
	}

	sb.WriteString("\n")
	sb.WriteString("  %% Styling classes\n")
	sb.WriteString("  classDef default fill:#f9fbfd,stroke:#3b82f6,stroke-width:1px;\n")
	return sb.String()
}

// ToDOT generates a Graphviz DOT representation of the boundary graph.
func (g *Graph) ToDOT() string {
	var sb strings.Builder
	sb.WriteString("digraph ArchitecturalBoundaries {\n")
	sb.WriteString("  rankdir=LR;\n")
	sb.WriteString("  node [shape=box, style=\"rounded,filled\", fillcolor=\"#f0f4f8\", fontname=\"Helvetica\"];\n")
	sb.WriteString("  edge [fontname=\"Helvetica\", fontsize=10];\n\n")

	if len(g.Rules) == 0 {
		sb.WriteString("  \"No boundary rules declared in .kern/boundaries.json\" [shape=note];\n")
		sb.WriteString("}\n")
		return sb.String()
	}

	for _, r := range g.Rules {
		action := strings.ToLower(r.Action)
		label := r.Action
		if r.Reason != "" {
			label = fmt.Sprintf("%s (%s)", r.Action, r.Reason)
		}

		if action == "forbid" {
			sb.WriteString(fmt.Sprintf("  \"%s\" -> \"%s\" [label=\"%s\", color=\"#dc2626\", style=\"dashed\", fontcolor=\"#dc2626\"];\n", r.From, r.To, label))
		} else {
			sb.WriteString(fmt.Sprintf("  \"%s\" -> \"%s\" [label=\"%s\", color=\"#2563eb\", fontcolor=\"#2563eb\"];\n", r.From, r.To, label))
		}
	}

	sb.WriteString("}\n")
	return sb.String()
}

// ToJSON returns the formatted JSON representation of the boundary graph.
func (g *Graph) ToJSON() (string, error) {
	b, err := json.MarshalIndent(g, "", "  ")
	if err != nil {
		return "", err
	}
	return string(b), nil
}

func sanitizeID(name string) string {
	// Replace non-alphanumeric characters with underscores for valid Mermaid node IDs
	var sb strings.Builder
	for _, ch := range name {
		if (ch >= 'a' && ch <= 'z') || (ch >= 'A' && ch <= 'Z') || (ch >= '0' && ch <= '9') || ch == '_' {
			sb.WriteRune(ch)
		} else {
			sb.WriteRune('_')
		}
	}
	id := sb.String()
	if id == "" {
		return "node"
	}
	return id
}
