package intel

import (
	"container/list"
	"fmt"
	"strings"
	"testing"

	"github.com/JayveerPrajapati/kern/internal/index"
)

func TestWhyResolvesQualifiedName(t *testing.T) {
	root := writeTree(t, map[string]string{
		"go.mod":   "module demo\n\ngo 1.22\n",
		"db/db.go": "package db\n\n// Open returns a connection.\nfunc Open() {}\n",
		"main.go":  "package main\n\nimport \"demo/db\"\n\nfunc main() {\n\tdb.Open()\n}\n",
	})
	ix, err := index.Build(root)
	if err != nil {
		t.Fatal(err)
	}
	info, ok := Why(ix, "db.Open")
	if !ok {
		t.Fatalf("Why(db.Open) not found")
	}
	if info.Symbol.Name != "Open" {
		t.Errorf("resolved symbol = %q; want Open", info.Symbol.Name)
	}
	if len(info.Callers) == 0 {
		t.Fatal("expected a caller for db.Open")
	}
	if _, ok := Resolve(ix, "db.Open"); !ok {
		t.Fatal("Resolve(db.Open) failed")
	}
}

func TestRankedSearchDemotesGenerated(t *testing.T) {
	root := writeTree(t, map[string]string{
		"go.mod":            "module demo\n\ngo 1.22\n",
		"send.go":           "package api\n\n// Send delivers the payload.\nfunc Send() {}\n",
		"models/send.pb.go": "package models\n\n// Code generated by protoc-gen-go. DO NOT EDIT.\nfunc Send() {}\n",
	})
	ix, err := index.Build(root)
	if err != nil {
		t.Fatal(err)
	}
	if !ix.IsGenerated("models/send.pb.go") {
		t.Fatal("expected pb.go to be marked generated")
	}
	hits := RankedSearch(ix, "send", 10)
	if len(hits) < 2 {
		t.Fatalf("expected both Send symbols, got %d", len(hits))
	}
	if hits[0].File != "send.go" {
		t.Errorf("hand-written Send should rank first, got %s", hits[0].File)
	}
}

func TestRankedSearchGeneratedStillReachable(t *testing.T) {
	root := writeTree(t, map[string]string{
		"go.mod":            "module demo\n\ngo 1.22\n",
		"models/stub.pb.go": "package models\n\n// Code generated by protoc-gen-go. DO NOT EDIT.\nfunc Stub() {}\n",
	})
	ix, err := index.Build(root)
	if err != nil {
		t.Fatal(err)
	}
	hits := RankedSearch(ix, "stub", 10)
	if len(hits) != 1 {
		t.Fatalf("generated-only query should still return the stub, got %d", len(hits))
	}
}

func TestRankedSearchProseMatchesCamelCaseSegments(t *testing.T) {
	root := writeTree(t, map[string]string{
		"go.mod": "module demo\n\ngo 1.22\n",
		"app.go": `package main

// OrderStateMachine tracks order lifecycle states.
type OrderStateMachine struct{}

// Stateful is a single-word decoy.
func Stateful() {}

// Machine decoy without the state segment.
func Machine() {}
`,
	})
	ix, err := index.Build(root)
	if err != nil {
		t.Fatal(err)
	}
	hits := RankedSearch(ix, "state machine", 10)
	if len(hits) == 0 {
		t.Fatalf("expected prose query to hit a symbol")
	}
	if hits[0].Name != "OrderStateMachine" {
		t.Errorf("segment-matched symbol should rank first, got %s", hits[0].Name)
	}
}

func TestRankedSearchPluralFolding(t *testing.T) {
	root := writeTree(t, map[string]string{
		"go.mod": "module demo\n\ngo 1.22\n",
		"app.go": `package main

// UserService manages users.
func UserService() {}

// Machine decoy for the plural probe.
func Machine() {}
`,
	})
	ix, err := index.Build(root)
	if err != nil {
		t.Fatal(err)
	}
	hits := RankedSearch(ix, "user services", 10)
	if len(hits) == 0 {
		t.Fatalf("plural query should still hit the singular segment")
	}
	if hits[0].Name != "UserService" {
		t.Errorf("plural-folded match should rank first, got %s", hits[0].Name)
	}
}

func TestRankedSearchDiacriticsNormalized(t *testing.T) {
	root := writeTree(t, map[string]string{
		"go.mod": "module demo\n\ngo 1.22\n",
		"app.go": `package main

// ResolveResolution untangles nested results.
func ResolveResolution() {}
`,
	})
	ix, err := index.Build(root)
	if err != nil {
		t.Fatal(err)
	}
	hits := RankedSearch(ix, "résolution", 10)
	if len(hits) == 0 {
		t.Fatalf("accented query should normalize to a segment match")
	}
	if hits[0].Name != "ResolveResolution" {
		t.Errorf("diacritic-normalized match should rank first, got %s", hits[0].Name)
	}
}

func TestRankedSearchCamelCaseQuerySplits(t *testing.T) {
	root := writeTree(t, map[string]string{
		"go.mod": "module demo\n\ngo 1.22\n",
		"app.go": `package main

// OrderStateMachine tracks order lifecycle states.
type OrderStateMachine struct{}

// Order decoy (single segment).
func Order() {}
`,
	})
	ix, err := index.Build(root)
	if err != nil {
		t.Fatal(err)
	}
	hits := RankedSearch(ix, "stateMachine", 10)
	if len(hits) == 0 {
		t.Fatalf("camelCase query should hit a symbol")
	}
	if hits[0].Name != "OrderStateMachine" {
		t.Errorf("camelCase query should rank the multi-segment symbol first, got %s", hits[0].Name)
	}
}

// TestRankedSearchNoTwoCharSubstringNoise locks the substring-tier minimum
// length: the query "ZzZzNopeNope" camelCase-splits to "zz"/"nope", and the
// 2-char "zz" must no longer substring-match every symbol containing a
// coincidental run (e.g. "Fuzzy") — 0 hits. A 2-char WHOLE segment ("db")
// still matches through the exact-segment tier.
func TestRankedSearchNoTwoCharSubstringNoise(t *testing.T) {
	root := writeTree(t, map[string]string{
		"go.mod": "module demo\n\ngo 1.22\n",
		"app.go": `package main

// FuzzySearch matches fuzzy substrings.
func FuzzySearch() {}

// GetDBConnection opens a database connection.
func GetDBConnection() {}
`,
	})
	ix, err := index.Build(root)
	if err != nil {
		t.Fatal(err)
	}
	if hits := RankedSearch(ix, "ZzZzNopeNope", 10); len(hits) != 0 {
		t.Fatalf("2-char substring query must return 0 hits, got %d (%v)", len(hits), hits)
	}
	hits := RankedSearch(ix, "db", 10)
	if len(hits) == 0 {
		t.Fatal("2-char whole-segment query should still match")
	}
	if hits[0].Name != "GetDBConnection" {
		t.Errorf("2-char segment query should hit GetDBConnection, got %s", hits[0].Name)
	}
}

// fakeEmbedder returns a bag-of-words dense vector so tests can predict cosine
// similarity without an Ollama server. Two texts share the same vector exactly
// when they contain the same whitespace-token set.
type fakeEmbedder struct{}

func (fakeEmbedder) EmbedText(text string) ([]float32, error) {
	const dim = 64
	vec := make([]float32, dim)
	for i, tok := range strings.Fields(strings.ToLower(text)) {
		idx := (hashToken(tok) + i) % dim
		vec[idx] = 1
	}
	return vec, nil
}

func hashToken(tok string) int {
	h := 0
	for _, r := range tok {
		h = h*31 + int(r)
	}
	if h < 0 {
		h = -h
	}
	return h
}

func TestSemanticSearchFallsBackWithoutEmbedder(t *testing.T) {
	root := writeTree(t, map[string]string{
		"go.mod": "module demo\n\ngo 1.22\n",
		"app.go": `package main

// OrderStateMachine tracks order lifecycle states.
type OrderStateMachine struct{}
`,
	})
	ix, err := index.Build(root)
	if err != nil {
		t.Fatal(err)
	}
	hits := SemanticSearch(ix, "order", 10, nil)
	if len(hits) == 0 {
		t.Fatal("SemanticSearch with nil embedder should degrade to RankedSearch")
	}
	if hits[0].Name != "OrderStateMachine" {
		t.Errorf("expected OrderStateMachine, got %s", hits[0].Name)
	}
}

func TestSemanticSearchReordersByMeaning(t *testing.T) {
	// The n-gram matcher ranks "Login" above "AuthenticateUser" for the query
	// "login", but the dense pass describes "AuthenticateUser" with
	// "authenticate" tokens too, so it must not disappear from results and must
	// surface in the top-k together with Login.
	root := writeTree(t, map[string]string{
		"go.mod": "module demo\n\ngo 1.22\n",
		"auth.go": `package auth

// Login signs a user in.
func Login() {}

// AuthenticateUser verifies credentials and opens a session.
func AuthenticateUser() {}
`,
	})
	ix, err := index.Build(root)
	if err != nil {
		t.Fatal(err)
	}
	hits := SemanticSearch(ix, "login", 10, fakeEmbedder{})
	if len(hits) == 0 {
		t.Fatal("expected semantic hits")
	}
	if hits[0].Name != "Login" {
		t.Errorf("exact name match should still lead after re-rank, got %s", hits[0].Name)
	}
}

func TestSemanticSearchLimited(t *testing.T) {
	root := writeTree(t, map[string]string{
		"go.mod": "module demo\n\ngo 1.22\n",
		"app.go": `package main

// FirstDecoy is unrelated.
func FirstDecoy() {}

// SecondDecoy is unrelated too.
func SecondDecoy() {}

// ThirdDecoy also unrelated.
func ThirdDecoy() {}

// FourthDecoy as well.
func FourthDecoy() {}

// FifthDecoy again.
func FifthDecoy() {}
`,
	})
	ix, err := index.Build(root)
	if err != nil {
		t.Fatal(err)
	}
	hits := SemanticSearch(ix, "decoy", 3, fakeEmbedder{})
	if len(hits) > 3 {
		t.Errorf("SemanticSearch should respect limit, got %d", len(hits))
	}
	if len(hits) == 0 {
		t.Fatal("expected hits")
	}
}

func TestSemanticSearchDescriptCacheBounded(t *testing.T) {
	// Push many UNIQUE descriptors through the cache and confirm it does not
	// grow without bound (a new key evicts one old key past the cap) and that
	// eviction is LRU — with no intervening hits the least-recently-used key
	// is the oldest inserted one, which must go first (deterministic, not
	// random).
	symbolEmbedMu.Lock()
	oldCache := symbolEmbedCache
	oldOrder := symbolEmbedOrder
	symbolEmbedCache = map[string]*embedCacheEntry{}
	symbolEmbedOrder = list.List{}
	symbolEmbedMu.Unlock()
	defer func() {
		symbolEmbedMu.Lock()
		symbolEmbedCache = oldCache
		symbolEmbedOrder = oldOrder
		symbolEmbedMu.Unlock()
	}()
	const extra = 50
	for i := 0; i < symbolEmbedCap+extra; i++ {
		desc := fmt.Sprintf("func Symbol%d file.go", i)
		if _, err := embedCached(fakeEmbedder{}, desc); err != nil {
			t.Fatal(err)
		}
	}
	symbolEmbedMu.Lock()
	size := len(symbolEmbedCache)
	orderLen := symbolEmbedOrder.Len()
	oldest := symbolEmbedCache["func Symbol0 file.go"]
	newest := symbolEmbedCache[fmt.Sprintf("func Symbol%d file.go", symbolEmbedCap+extra-1)]
	symbolEmbedMu.Unlock()
	if size > symbolEmbedCap {
		t.Errorf("cache exceeded cap: %d > %d", size, symbolEmbedCap)
	}
	if size != symbolEmbedCap {
		t.Errorf("cache size = %d, want %d (cap, after evicting the oldest %d)", size, symbolEmbedCap, extra)
	}
	if orderLen != symbolEmbedCap {
		t.Errorf("LRU recency list length = %d, want %d (one entry per cached key)", orderLen, symbolEmbedCap)
	}
	if oldest != nil {
		t.Error("oldest inserted descriptor must be evicted first (LRU: least recently used), but it is still cached")
	}
	if newest == nil {
		t.Error("newest inserted descriptor must be retained under LRU eviction")
	}
}

// TestSymbolEmbedCacheLRUHitRefreshesRecency: a hit must refresh a key's
// recency so hot entries survive cold scans — under FIFO the hot entry would
// be the oldest-inserted and get evicted first.
func TestSymbolEmbedCacheLRUHitRefreshesRecency(t *testing.T) {
	symbolEmbedMu.Lock()
	oldCap, oldCache, oldOrder := symbolEmbedCap, symbolEmbedCache, symbolEmbedOrder
	symbolEmbedCap = 3
	symbolEmbedCache = map[string]*embedCacheEntry{}
	symbolEmbedOrder = list.List{}
	symbolEmbedMu.Unlock()
	defer func() {
		symbolEmbedMu.Lock()
		symbolEmbedCap, symbolEmbedCache, symbolEmbedOrder = oldCap, oldCache, oldOrder
		symbolEmbedMu.Unlock()
	}()

	e := fakeEmbedder{}
	for _, desc := range []string{"a", "b", "c"} {
		if _, err := embedCached(e, desc); err != nil {
			t.Fatalf("embed %q: %v", desc, err)
		}
	}
	// Hit "a" — refreshes its recency (moves it to the most-recently-used end).
	if _, err := embedCached(e, "a"); err != nil {
		t.Fatalf("re-embed a: %v", err)
	}
	// Insert "d": evicts the least-recently-used ("b"), NOT the hot "a".
	if _, err := embedCached(e, "d"); err != nil {
		t.Fatalf("embed d: %v", err)
	}
	// Insert "e": evicts the next-least-recently-used ("c"). "a" survives two
	// cold scans only because its hit refreshed recency. (Assertions probe via
	// cachedEmbedding only AFTER all inserts: probes refresh recency too.)
	if _, err := embedCached(e, "e"); err != nil {
		t.Fatalf("embed e: %v", err)
	}
	for _, gone := range []string{"b", "c"} {
		if _, ok := cachedEmbedding(gone); ok {
			t.Errorf("LRU violation: %q (least recently used) should have been evicted", gone)
		}
	}
	for _, want := range []string{"a", "d", "e"} {
		if _, ok := cachedEmbedding(want); !ok {
			t.Errorf("expected %q still cached (hot / recently inserted), got evicted", want)
		}
	}
}

// TestRankedSearchExactNameOutranksSuperstring (F-SE1): the exact symbol must
// rank first — TestWriteFileAtomic (a superstring match) used to outrank
// WriteFileAtomic itself, and agents take the top hit.
func TestRankedSearchExactNameOutranksSuperstring(t *testing.T) {
	ix := &index.Index{}
	ix.Symbols = []index.Symbol{
		{Name: "WriteFileAtomic", Kind: "func", File: "fsutil.go", Line: 13},
		{Name: "TestWriteFileAtomic", Kind: "func", File: "fsutil_test.go", Line: 9},
		{Name: "TestCheckPurityFlagsSibling", Kind: "func", File: "purity_test.go", Line: 94},
	}
	hits := RankedSearchScored(ix, "WriteFileAtomic", 5)
	if len(hits) == 0 || hits[0].Symbol.Name != "WriteFileAtomic" {
		t.Fatalf("exact symbol must rank first, got %+v", hits)
	}
}
