package intel

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/JayveerPrajapati/kern/internal/index"
)

// WikiExport writes a markdown wiki into outDir: an index README plus one page
// per package directory listing every symbol with its kind, signature, doc
// comment, source location, and callers. When obsidian is set, pages carry
// Obsidian-style YAML frontmatter and caller references are rendered as
// [[wikilinks]]; the README index page is unchanged. Returns the paths written.
func WikiExport(ix *index.Index, outDir string, obsidian bool) ([]string, error) {
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return nil, err
	}
	type pkg struct {
		dir     string
		symbols []index.Symbol
	}
	byDir := map[string][]index.Symbol{}
	for _, s := range ix.Symbols {
		d := filepath.Dir(s.File)
		if d == "." {
			d = filepath.Base(ix.Root)
		}
		byDir[d] = append(byDir[d], s)
	}
	dirs := make([]string, 0, len(byDir))
	for d := range byDir {
		dirs = append(dirs, d)
	}
	sort.Strings(dirs)

	var written []string
	total := 0
	var pages strings.Builder
	for _, d := range dirs {
		syms := byDir[d]
		sort.Slice(syms, func(i, j int) bool {
			if syms[i].Kind != syms[j].Kind {
				return syms[i].Kind < syms[j].Kind
			}
			return syms[i].FullName() < syms[j].FullName()
		})
		total += len(syms)
		page, err := wikiPage(ix, d, syms, obsidian)
		if err != nil {
			return nil, err
		}
		rel := wikiSlug(d) + ".md"
		path := filepath.Join(outDir, rel)
		if err := os.WriteFile(path, []byte(page), 0o644); err != nil {
			return nil, err
		}
		written = append(written, rel)
		fmt.Fprintf(&pages, "- [%s](%s) — %d symbols\n", d, rel, len(syms))
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# Community wiki\n\n")
	fmt.Fprintf(&b, "Auto-generated by `kern wiki` from the call-graph index.\n\n")
	fmt.Fprintf(&b, "- **total symbols:** %d\n- **package directories:** %d\n- **source files:** %d\n\n",
		total, len(dirs), len(ix.SymbolsByFile))
	b.WriteString("\n## Packages\n\n")
	b.WriteString(pages.String())
	readme := filepath.Join(outDir, "README.md")
	if err := os.WriteFile(readme, []byte(b.String()), 0o644); err != nil {
		return nil, err
	}
	written = append([]string{"README.md"}, written...)
	return written, nil
}

// wikiSlug maps a package directory to a safe markdown file name.
func wikiSlug(dir string) string {
	r := strings.NewReplacer("\\", "_", "/", "_", " ", "_", ".", "_")
	s := r.Replace(dir)
	if s == "" {
		s = "root"
	}
	return s
}

// wikiPage renders the markdown page for one package directory. When obsidian
// is true the page is prefixed with Obsidian-style YAML frontmatter and caller
// references are rendered as Obsidian [[wikilinks]]; when false the output is
// the plain markdown format.
func wikiPage(ix *index.Index, dir string, syms []index.Symbol, obsidian bool) (string, error) {
	var b strings.Builder
	if obsidian {
		b.WriteString(obsidianFrontmatter(ix, dir, syms))
	}
	fmt.Fprintf(&b, "# package %s\n\nSymbols: %d\n\n", dir, len(syms))
	var fileMap map[string]string
	if obsidian {
		fileMap = buildFileMap(ix)
	}
	for _, s := range syms {
		doc := docComment(ix.Root, s.File, s.Line)
		fmt.Fprintf(&b, "## %s %s\n\n", s.Kind, s.FullName())
		if doc != "" {
			b.WriteString(doc)
			b.WriteString("\n\n")
		}
		fmt.Fprintf(&b, "- source: `%s:%d`\n", s.File, s.Line)
		if len(s.Params) > 0 {
			fmt.Fprintf(&b, "- params: `%s`\n", strings.Join(s.Params, ", "))
		}
		if callers := ix.CallersFor(s); len(callers) > 0 {
			refs := callers
			if obsidian {
				refs = obsidianLinks(ix, fileMap, callers)
			}
			fmt.Fprintf(&b, "- callers (%d): %s\n", len(callers), strings.Join(refs, ", "))
		}
		b.WriteString("\n")
	}
	return b.String(), nil
}

// obsidianFrontmatter returns the Obsidian-style YAML frontmatter for a page:
// title and file name the package dir, community is the first non-empty
// community label among the page's symbols ("none" when none has one), and
// hub reports whether any symbol in the dir ranks as a hub.
func obsidianFrontmatter(ix *index.Index, dir string, syms []index.Symbol) string {
	labels := ix.CommunityLabels()
	label := "none"
	for _, s := range syms {
		if l := labels[s.FullName()]; l != "" {
			label = l
			break
		}
	}
	hubs := hubSet(ix)
	hub := false
	for _, s := range syms {
		if hubs[s.FullName()] {
			hub = true
			break
		}
	}
	return fmt.Sprintf("---\ntitle: %s\ncommunity: %s\nfile: %s\nhub: %t\n---\n\n", dir, label, dir, hub)
}

// obsidianLinks renders caller references as Obsidian wikilinks
// "[[<page-slug>|<name>]]" when the referenced symbol has a resolvable
// definition file; references without a resolvable file stay plain names.
func obsidianLinks(ix *index.Index, fileMap map[string]string, names []string) []string {
	out := make([]string, len(names))
	for i, n := range names {
		file, ok := fileMap[n]
		if !ok || file == "" {
			out[i] = n
			continue
		}
		d := filepath.Dir(file)
		if d == "." {
			d = filepath.Base(ix.Root)
		}
		out[i] = fmt.Sprintf("[[%s|%s]]", wikiSlug(d), n)
	}
	return out
}
