package sec

import (
	"reflect"
	"strings"
	"testing"
)

func TestGenPytestScaffold(t *testing.T) {
	tf := TaintFinding{
		Finding: Finding{
			File:     "app.py",
			Line:     9,
			Rule:     "py-os-system",
			Severity: "error",
			Message:  "shell command execution via os.system()/os.popen()",
		},
		Func:    "os.system",
		Tainted: true,
	}
	sc := GenPytestScaffold(tf)

	if sc.File != "app_taint_test.py" {
		t.Errorf("File = %q, want app_taint_test.py", sc.File)
	}
	if !strings.Contains(sc.Code, "import pytest") {
		t.Errorf("scaffold missing 'import pytest':\n%s", sc.Code)
	}
	if !strings.Contains(sc.Code, "Auto-generated by kern taint --generate") {
		t.Errorf("scaffold missing auto-generated docstring:\n%s", sc.Code)
	}
	if !strings.Contains(sc.Code, "TODO: implement the probe below") {
		t.Errorf("scaffold missing TODO docstring:\n%s", sc.Code)
	}
	if !strings.Contains(sc.Code, "# source: app.py:9 — shell command execution via os.system()/os.popen()") {
		t.Errorf("scaffold missing source comment:\n%s", sc.Code)
	}
	if !strings.Contains(sc.Code, "def test_py_os_system_9():") {
		t.Errorf("scaffold missing test function name:\n%s", sc.Code)
	}
	if !strings.Contains(sc.Code, "TODO") || !strings.Contains(sc.Code, "...") {
		t.Errorf("scaffold missing TODO probe body:\n%s", sc.Code)
	}
}

func TestGenPytestScaffoldDeterministic(t *testing.T) {
	tf := TaintFinding{
		Finding: Finding{
			File:     "svc/db.py",
			Line:     42,
			Rule:     "py-sql-format",
			Severity: "error",
			Message:  "dynamic SQL built with an f-string",
		},
		Tainted: true,
	}
	a := GenPytestScaffold(tf)
	b := GenPytestScaffold(tf)
	if !reflect.DeepEqual(a, b) {
		t.Fatalf("GenPytestScaffold not deterministic:\na=%+v\nb=%+v", a, b)
	}
	if a.File != "svc/db_taint_test.py" {
		t.Errorf("File = %q, want svc/db_taint_test.py", a.File)
	}
}

func TestScaffoldForDispatch(t *testing.T) {
	py := TaintFinding{
		Finding: Finding{File: "app.py", Line: 1, Rule: "py-eval", Message: "dynamic code evaluation via eval()"},
		Tainted: true,
	}
	if sc := ScaffoldFor(py); !strings.HasSuffix(sc.File, "_taint_test.py") || !strings.Contains(sc.Code, "import pytest") {
		t.Errorf("ScaffoldFor(.py) = %+v, want pytest scaffold", sc)
	}

	// A py-* rule on a non-.py file still selects the pytest scaffold.
	odd := TaintFinding{
		Finding: Finding{File: "snippet.txt", Line: 3, Rule: "py-exec", Message: "dynamic code execution via exec()"},
		Tainted: true,
	}
	if sc := ScaffoldFor(odd); !strings.HasSuffix(sc.File, "_taint_test.py") || !strings.Contains(sc.Code, "def test_py_exec_3") {
		t.Errorf("ScaffoldFor(py-* rule) = %+v, want pytest scaffold", sc)
	}

	// Go findings keep the go test scaffold.
	goFinding := TaintFinding{
		Finding: Finding{File: "svc/handlers.go", Line: 12, Rule: "sql-injection", Severity: "error", Message: "dynamic SQL built from variables"},
		Func:    "lookup", Tainted: true, EntryPoint: "H", Path: []string{"H", "lookup"},
	}
	sc := ScaffoldFor(goFinding)
	if !strings.HasSuffix(sc.File, "_taint_test.go") {
		t.Errorf("ScaffoldFor(.go) = %+v, want go test scaffold", sc)
	}
	if !strings.Contains(sc.Code, "func TestTaintSQLInjection12(t *testing.T)") {
		t.Errorf("ScaffoldFor(.go) code = %q, want Go TestTaint function", sc.Code)
	}
}
