package sec

import (
	"fmt"
	"path/filepath"
	"strings"
)

// pyProbeComments maps a Python rule id to the deterministic probe instruction
// embedded in the generated pytest body.
var pyProbeComments = map[string]string{
	"py-eval":             "assert the expression passed to eval cannot be influenced by untrusted input",
	"py-exec":             "assert exec input is validated and cannot inject code",
	"py-os-system":        "assert shell input is validated before os.system execution",
	"py-subprocess-shell": "assert the shell command cannot be built from untrusted input",
	"py-subprocess":       "assert subprocess always runs with shell=False and non-shell arguments",
	"py-pickle-load":      "assert untrusted pickle payloads are rejected",
	"py-yaml-load":        "assert yaml.load always uses a safe Loader",
	"py-sql-format":       "assert SQL queries are parameterized, never formatted from variables",
}

// pyProbeFor returns the deterministic probe instruction for a Python rule,
// falling back to a generic instruction for unknown rules.
func pyProbeFor(rule string) string {
	if p := pyProbeComments[rule]; p != "" {
		return p
	}
	return "probe input validation at this sink"
}

// GenPytestScaffold builds a deterministic pytest frame for a tainted Python
// sink (G-4). The output file is <sink dir>/<sink base>_taint_test.py; the
// test function is test_<rule>_<line> (rule dashes become underscores so the
// name is a valid Python identifier). The probe body is intentionally left
// for the caller (LLM-assisted fill); the frame itself is deterministic.
func GenPytestScaffold(t TaintFinding) TestScaffold {
	dir := filepath.Dir(t.File)
	base := filepath.Base(t.File)
	stem := strings.TrimSuffix(base, filepath.Ext(base))
	outFile := filepath.Join(dir, stem+"_taint_test.py")

	rule := t.Rule
	if rule == "" {
		rule = "py-unknown"
	}
	testName := "test_" + strings.ReplaceAll(rule, "-", "_") + fmt.Sprintf("_%d", t.Line)
	via := "source"
	if t.EntryPoint != "" {
		via = t.EntryPoint
	}
	probe := pyProbeFor(rule)
	code := fmt.Sprintf(`"""Auto-generated by kern taint --generate (G-4).

TODO: implement the probe below — craft input that reaches %s:%d (%s) and
assert the sink is not exploitable. This frame is a deterministic starting
point for LLM-assisted fill.
"""

import pytest

# source: %s:%d — %s
def %s():
    # TODO: craft input that reaches %s:%d and assert safe handling
    # (%s; tainted via %s)
    ...
`,
		t.File, t.Line, rule,
		t.File, t.Line, t.Message,
		testName,
		t.File, t.Line, probe, via)

	return TestScaffold{File: outFile, Code: code}
}

// ScaffoldFor returns the language-appropriate test scaffold for a tainted
// finding (G-4): a pytest frame when the sink is a Python file or a py-*
// rule, the Go frame otherwise.
func ScaffoldFor(t TaintFinding) TestScaffold {
	if strings.HasSuffix(strings.ToLower(t.File), ".py") || strings.HasPrefix(t.Rule, "py-") {
		return GenPytestScaffold(t)
	}
	return GenTestScaffold(t)
}
