// Package gates is the authoritative registry of Blueprint's phase gates
// (G0-G29). A gate is a capability milestone backed by at least one test that
// proves the capability. The registry is compiled into the binary (NOT a
// manifest file), so `blueprint doctor --json` reads it with no file I/O and
// it can never drift from the code that ships it.
//
// The bidirectional mapping between registry entries and test files is
// enforced by TestRegistryBidirectionalMapping in registry_test.go: every
// entry must point at a real test file containing every listed test function,
// and every gate-named test in the repo (TestG<NN>_*, plus G14's
// TestContract*, and the primary-adapter families TestGitleaks* for G3 and
// TestJSCPD* for G6) must be claimed by exactly one registry entry.
package gates

// Gate describes one phase gate: what it verifies, how it enforces, and which
// test(s) prove it.
type Gate struct {
	// ID is the stable gate identifier, "G0" through "G29".
	ID string
	// Name is a short human-readable name for the gate.
	Name string
	// Verifies is 1-2 sentences describing what the gate verifies.
	Verifies string
	// Enforcement is the gate's enforcement level: "block" (hard fail on
	// violation), "warn" (advisory, does not fail the build), "skip", or
	// "info" (informational only). `blueprint doctor --json` reports it per
	// gate.
	Enforcement string
	// TestFile is the repo-relative path of the gate's PRIMARY test file
	// (e.g. "cmd/blueprint/g0_test.go"). A gate's TestFuncs may span more
	// than one file: TestFile names the file holding most of them, and the
	// forward-mapping test resolves the rest via a whole-repo fallback (see
	// TestRegistryForwardMapping).
	TestFile string
	// TestFuncs are the names of the test functions that back this gate
	// (e.g. "TestG0_BaselineBuildsAndVets"). Most live in TestFile; a few
	// may be declared in other test files of the same package.
	TestFuncs []string
	// Package is the Go package the test file lives in ("main", "service",
	// "kern", ...).
	Package string
}

// Registry is the complete, ordered list of all 30 phase gates, G0 through
// G29. It is the single source of truth for gate inventory; docs/gates.md is
// generated from it by hand and must stay in sync (the orphan test checks the
// test-file mapping, and TestRegistryShape pins the count and IDs).
var Registry = []Gate{
	{
		ID:          "G0",
		Name:        "Baseline build & vets",
		Verifies:    "Baseline builds+vets, ownership docs exist, exit-code contract",
		Enforcement: "block",
		TestFile:    "cmd/blueprint/g0_test.go",
		TestFuncs: []string{
			"TestG0_BaselineBuildsAndVets",
			"TestG0_OwnershipDocsExist",
			"TestG0_ExitCodeContract",
		},
		Package: "main",
	},
	{
		ID:          "G1",
		Name:        "Validation engine",
		Verifies:    "PASS/BLOCK aggregation, precedence ERROR>BLOCK, JSON, SKIP",
		Enforcement: "block",
		TestFile:    "internal/blueprint/service/validate_test.go",
		TestFuncs: []string{
			"TestG1_ValidChange_PASS",
			"TestG1_ArchitectureViolation_BLOCK",
			"TestG1_EmptyChange_PASS",
			"TestG1_MultipleFindings_AllPreserved",
			"TestG1_BlockPlusWarns_BLOCK",
			"TestG1_CheckError_ERROR",
			"TestG1_ErrorDominatesBlock",
			"TestG1_JSONStableParseable",
			"TestG1_AllSkipped_SKIP",
		},
		Package: "service",
	},
	{
		ID:          "G2",
		Name:        "Architecture/boundary enforcement",
		Verifies:    "Architecture/boundary enforcement via kern guard",
		Enforcement: "block",
		TestFile:    "internal/blueprint/adapters/kern/g2_test.go",
		TestFuncs: []string{
			"TestG2_ArchitectureClean",
			"TestG2_LegalDependency",
			"TestG2_IllegalDependency",
			"TestG2_MultipleViolations",
			"TestG2_PreexistingViolationUnrelatedChange",
			"TestG2_PreexistingViolation_StrictBaseline",
			"TestG2_RenameScenario",
			"TestG2_NewFileScenario",
			"TestG2_DeletedImportScenario",
			"TestG2_CLI_EndToEnd",
		},
		Package: "kern",
	},
	{
		ID:          "G3",
		Name:        "Secret detection & redaction",
		Verifies:    "Secret detection + redaction (gitleaks adapter primary, kern sec fallback)",
		Enforcement: "block",
		TestFile:    "internal/blueprint/adapters/kern/g3_test.go",
		TestFuncs: []string{
			"TestG3_ObviousAPIKey",
			"TestG3_PasswordAssignment",
			"TestG3_PrivateKey",
			"TestG3_TokenInJSON",
			"TestG3_TokenInYAML",
			"TestG3_FalsePositiveTestFixture",
			"TestG3_FalsePositiveNoAllowlist",
			"TestG3_RedactionPlainText",
			"TestG3_RedactionJSON",
			"TestG3_RedactionLogs",
			// Primary adapter (wired first in buildCheckList): gitleaks.
			"TestGitleaksCheckEmptyChange",
			"TestGitleaksCheckMissingRepoRoot",
			"TestGitleaksCheckOnDiskFile",
			"TestGitleaksCheckPathEscapeRejected",
			"TestGitleaksCheckVersionProbeFailure",
			"TestGitleaksFallbackInHouseBlocks",
			"TestGitleaksFallbackInHousePassWarns",
			"TestGitleaksFallbackNoClient",
			"TestGitleaksFallbackInHouseErrorPreserved",
			"TestGitleaksAllowlistSuppressesTestFixtures",
			"TestGitleaksAllowlistOnlyTestFixturePasses",
			"TestGitleaksAllowlistTestdataAndJSTestFixtures",
		},
		Package: "kern",
	},
	{
		ID:          "G4",
		Name:        "Pre-commit hook via CLI",
		Verifies:    "Pre-commit hook: clean/block/JSON/bypass/idempotent/foreign-hook",
		Enforcement: "block",
		TestFile:    "cmd/blueprint/g4_test.go",
		TestFuncs: []string{
			"TestG4_CleanCommit",
			"TestG4_ArchitectureViolation",
			"TestG4_SecretViolation",
			"TestG4_MultipleFindings",
			"TestG4_StagedDiffersFromWorkingTree",
			"TestG4_DeletedFile",
			"TestG4_Rename",
			"TestG4_BinaryFile",
			"TestG4_EmptyCommit",
			"TestG4_HookFailure",
			"TestG4_BlueprintBinaryUnavailable",
			"TestG4_ExplicitBypassDocumented",
			"TestG4_InstallHookIdempotent",
			"TestG4_InstallHookRefusesForeign",
			"TestG4_JSONFormat",
		},
		Package: "main",
	},
	{
		ID:          "G5",
		Name:        "MCP validate_staged tool",
		Verifies:    "MCP server validate_staged tool",
		Enforcement: "block",
		TestFile:    "internal/blueprint/mcp/g5_test.go",
		TestFuncs: []string{
			"TestG5_ValidFileWrite",
			"TestG5_ArchitectureViolation",
			"TestG5_SecretInsertion",
			"TestG5_MultiFileChange",
			"TestG5_StagedDuplicationWarn",
			"TestG5_FailedToolExecution",
			"TestG5_MalformedPayload",
			"TestG5_OversizedPayload",
			"TestG5_MissingRepoContext",
			"TestG5_AgentIdentityMissing",
			"TestG5_BlockedResponseMachineReadable",
			"TestG5_RepairAndRetry",
			"TestG5_ServerEndToEnd",
		},
		Package: "mcp",
	},
	{
		ID:          "G6",
		Name:        "Duplication check",
		Verifies:    "Duplication: precision/recall on 7 fixtures, never-blocks, format",
		Enforcement: "warn",
		TestFile:    "internal/blueprint/checks/duplication/g6_test.go",
		TestFuncs: []string{
			"TestG6_ExactDuplicate",
			"TestG6_Metrics",
			"TestG6_NeverBlocks",
			"TestG6_FindingFormat",
			"TestG6_EmptyChange",
			"TestG6_NoExistingFiles",
			"TestG6_FixturesExist",
			// Primary adapter (wired first in buildCheckList): jscpd.
			"TestJSCPDCheckEmptyChange",
			"TestJSCPDCheckMissingRepoRoot",
			"TestJSCPDCheckOnDiskFile",
			"TestJSCPDCheckPathEscapeRejected",
			"TestJSCPDCheckLaunchFailure",
			"TestJSCPDCheckFragmentTruncated",
			"TestJSCPDFallbackInHousePassWarns",
			"TestJSCPDFallbackNoClient",
			"TestJSCPDFallbackInHouseErrorPreserved",
			"TestJSCPDTwoPassConfirmedBlock",
			"TestJSCPDTwoPassNotConfirmedStaysAdvisory",
			"TestJSCPDTwoPassMockConfirmer",
			"TestJSCPDFallbackAdvisoryStaysWarn",
		},
		Package: "duplication",
	},
	{
		ID:          "G7",
		Name:        "Agent repair loop & feedback",
		Verifies:    "Agent repair loop + feedback contract (BLOCK carries evidence)",
		Enforcement: "block",
		TestFile:    "internal/blueprint/adapters/kern/g7_test.go",
		TestFuncs: []string{
			"TestG7_ArchitectureRepairLoop",
			"TestG7_SecretRepairLoop",
			"TestG7_MCPRepairLoop",
			"TestG7_FeedbackContractAudit",
			"TestG7_VagueResponseRejected",
		},
		Package: "kern",
	},
	{
		ID:          "G8",
		Name:        "Sandboxed build/test isolation",
		Verifies:    "Sandboxed build/test isolation",
		Enforcement: "block",
		TestFile:    "internal/blueprint/sandbox/g8_test.go",
		TestFuncs: []string{
			"TestG8_SuccessfulBuild",
			"TestG8_FailingBuild",
			"TestG8_FailingTest",
			"TestG8_Timeout",
			"TestG8_ProcessTreeCleanup",
			"TestG8_LargeStdout",
			"TestG8_LargeStderr",
			"TestG8_ConcurrentRuns",
			"TestG8_Cancellation",
			"TestG8_CleanupAfterFailure",
			"TestG8_RepoUntouched",
			"TestG8_SandboxCheckPass",
			"TestG8_SandboxCheckFailingBuild",
			"TestG8_SandboxCheckFailingTest",
		},
		Package: "sandbox",
	},
	{
		ID:          "G9",
		Name:        "Resilience scenarios",
		Verifies:    "Resilience: injected timeouts, network leakage, cleanup, shell scenarios",
		Enforcement: "warn",
		TestFile:    "internal/blueprint/resilience/g9_test.go",
		TestFuncs: []string{
			"TestG9_BaselinePasses",
			"TestG9_InjectedTimeoutActuallyInjected",
			"TestG9_ResilientImplPasses",
			"TestG9_NonResilientImplFails",
			"TestG9_FailuresRepeatable",
			"TestG9_NoNetworkLeakage",
			"TestG9_CleanupGuaranteed",
			"TestG9_Applicability",
			"TestG9_Registry",
			"TestG9_ShellScenariosRegistered",
			"TestG9_ShellScenarioDetectsFailure",
			"TestG9_ShellScenarioPassesWhenHandled",
			"TestG9_ShellApplicabilityAndDetection",
		},
		Package: "resilience",
	},
	{
		ID:          "G10",
		Name:        "Watcher robustness",
		Verifies:    "Watcher: bursty edits, rename, delete, temp files, CPU idle, shutdown",
		Enforcement: "warn",
		TestFile:    "internal/blueprint/watcher/g10_test.go",
		TestFuncs: []string{
			"TestG10_BurstyEdits",
			"TestG10_FileRename",
			"TestG10_FileDelete",
			"TestG10_EditorTempFiles",
			"TestG10_IgnoredPaths",
			"TestG10_GeneratedFiles",
			"TestG10_SimultaneousEdits",
			"TestG10_StaleEventOrdering",
			"TestG10_WatcherRestart",
			"TestG10_Shutdown",
			"TestG10_CPUUsageIdle",
			"TestG10_ExtensionFilter",
			"TestG10_InitialSnapshotNoEvents",
			"TestG10_WalkErrorReported",
		},
		Package: "watcher",
	},
	{
		ID:          "G11",
		Name:        "CI command",
		Verifies:    "CI command: clean/block PR, determinism, JSON artifact, detached-head no-mutation",
		Enforcement: "block",
		TestFile:    "cmd/blueprint/g11_test.go",
		TestFuncs: []string{
			"TestG11_CleanPR",
			"TestG11_PolicyViolationPR",
			"TestG11_StaleConfig",
			"TestG11_MissingBinary",
			"TestG11_DeterministicAcrossRuns",
			"TestG11_JSONArtifactOutput",
			"TestG11_HumanReadableSummary",
			"TestG11_NoLocalDaemonState",
			"TestG11_EmptyPR",
			"TestG11_HeadRefWorktreeNoMutation",
		},
		Package: "main",
	},
	{
		ID:          "G12",
		Name:        "Metrics",
		Verifies:    "Metrics: latency benchmarks, persistence, cap, atomic save",
		Enforcement: "info",
		TestFile:    "internal/blueprint/metrics/g12_test.go",
		TestFuncs: []string{
			"TestG12_LatencyBenchmarks",
			"TestG12_ColdVsWarmIndex",
			"TestG12_MetricsRecording",
			"TestG12_MetricsPersistence",
			"TestG12_MetricsReset",
			"TestG12_LatencyCap",
			"TestG12_AtomicSaveRoundTrip",
		},
		Package: "metrics",
	},
	{
		ID:          "G13",
		Name:        "Fresh-machine end-to-end",
		Verifies:    "Fresh-machine end-to-end (build+install+MCP+check)",
		Enforcement: "block",
		TestFile:    "cmd/blueprint/g13_test.go",
		TestFuncs: []string{
			"TestG13_FreshMachineEndToEnd",
		},
		Package: "main",
	},
	{
		ID:          "G14",
		Name:        "Versioned kern contract",
		Verifies:    "Versioned kern contract, fail-closed",
		Enforcement: "block",
		TestFile:    "internal/blueprint/adapters/kern/contract_test.go",
		TestFuncs: []string{
			"TestContractGuardValidVersion",
			"TestContractGuardWrongVersion",
			"TestContractGuardMissingVersion",
			"TestContractGuardMalformed",
			"TestContractSecValid",
			"TestContractSecLegacyArray",
			"TestContractSecWrongVersion",
			"TestContractSecObjectMissingVersion",
		},
		Package: "kern",
	},
	{
		ID:          "G15",
		Name:        "Pre-write validation (validate_proposed)",
		Verifies:    "Pre-write validation for agents via validate_proposed",
		Enforcement: "block",
		TestFile:    "internal/blueprint/mcp/g15_test.go",
		TestFuncs: []string{
			"TestG15_ProposedSecretBlocked",
			"TestG15_ProposedCleanPass",
			"TestG15_ProposedMalformedArgs",
			"TestG15_ProposedSecretScanUsesContent",
			"TestG15_ProposedDuplicationWarn",
		},
		Package: "mcp",
	},
	{
		ID:          "G16",
		Name:        "Source-aware policy",
		Verifies:    "Source-aware policy (source override changes status, never passes block, warn cap)",
		Enforcement: "warn",
		TestFile:    "internal/blueprint/policy/engine_test.go",
		TestFuncs: []string{
			"TestG16_SourceOverrideChangesStatus",
			"TestG16_SourceOverrideNeverPassesBlock",
			"TestG16_SourceOverrideWarnModeCap",
			"TestG16_EmptySourceUsesGlobal",
			"TestG16_LoaderSourceValidation",
			"TestG16_ServiceSetsCheckResultSource",
		},
		Package: "policy",
	},
	{
		ID:          "G17",
		Name:        "Doctor preflight",
		Verifies:    "blueprint doctor preflight (env/config/git)",
		Enforcement: "info",
		TestFile:    "cmd/blueprint/doctor_test.go",
		TestFuncs: []string{
			"TestG17_Healthy",
			"TestG17_MissingKern",
			"TestG17_InvalidConfig",
			"TestG17_InvalidBoundaries",
			"TestG17_NoBoundariesWarns",
			"TestG17_JSONShape",
		},
		Package: "main",
	},
	{
		ID:          "G18",
		Name:        "Policy in MCP handlers",
		Verifies:    "Policy evaluator wired into MCP handlers",
		Enforcement: "block",
		TestFile:    "internal/blueprint/mcp/g18_test.go",
		TestFuncs: []string{
			"TestG18_PolicyAppliedViaMCP_WarnMode",
			"TestG18_PolicyAppliedViaMCP_SourceOverride",
			"TestG18_PolicyDefaultStillBlocks",
		},
		Package: "mcp",
	},
	{
		ID:          "G19",
		Name:        "Audit trail on validation",
		Verifies:    "Audit trail written on validation",
		Enforcement: "block",
		TestFile:    "cmd/blueprint/g19_test.go",
		TestFuncs: []string{
			"TestG19_CLICheckWritesAudit",
			"TestG19_ValidationWritesAudit",
			"TestG19_AuditFailureDoesNotFailValidation",
			"TestG19_EmptyChangeNoAudit",
		},
		Package: "main",
	},
	{
		ID:          "G20",
		Name:        "Suppressions & owners",
		Verifies:    "Suppressions + owners policy",
		Enforcement: "info",
		TestFile:    "internal/blueprint/policy/engine_test.go",
		TestFuncs: []string{
			"TestG20_SuppressionMatches",
			"TestG20_SuppressionRuleOnly",
			"TestG20_ExpiredSuppressionIgnored",
			"TestG20_OwnerAttached",
			"TestG20_SuppressionDoesNotAffectOtherRules",
			"TestG20_LoaderSuppressions",
			"TestG20_LoaderBadExpiry",
			"TestG20_AuditSuppressedMeta",
		},
		Package: "policy",
	},
	{
		ID:          "G21",
		Name:        "Duplication on-disk/content-path",
		Verifies:    "Duplication on-disk / content-path warn, confidence=similarity",
		Enforcement: "warn",
		TestFile:    "internal/blueprint/checks/duplication/g6_test.go",
		TestFuncs: []string{
			"TestG21_DuplicationWarnOnDisk",
			"TestG21_DuplicationContentPath",
			"TestG21_NoKernClient",
			"TestG21_ContractMismatch",
			"TestG21_ConfidenceEqualsSimilarityScore",
		},
		Package: "duplication",
	},
	{
		ID:          "G22",
		Name:        "blueprint fix command",
		Verifies:    "blueprint fix: proposed fix, confinement, worktree cleanup, JSON",
		Enforcement: "block",
		TestFile:    "cmd/blueprint/fix_test.go",
		TestFuncs: []string{
			"TestG22_CleanFix",
			"TestG22_FixBlockedBySecret",
			"TestG22_Confinement",
			"TestG22_NotARepo",
			"TestG22_WorktreeCleanedUp",
			"TestG22_JsonShape",
			"TestG22_NoFiles",
		},
		Package: "main",
	},
	{
		ID:          "G23",
		Name:        "Resilience check wiring",
		Verifies:    "Resilience check wiring / scenarios (YAML)",
		Enforcement: "warn",
		TestFile:    "cmd/blueprint/g23_test.go",
		TestFuncs: []string{
			"TestG23_ResilienceCheckWiring",
			"TestG23_ResilienceCheckWiringInvalidYAML",
		},
		Package: "main",
	},
	{
		ID:          "G24",
		Name:        "Latency budget gate",
		Verifies:    "Latency budget gate, strict-latency hard-fail",
		Enforcement: "block",
		TestFile:    "cmd/blueprint/g24_test.go",
		TestFuncs: []string{
			"TestG24_CIArtifactCarriesLatencyFindingAndChecks",
			"TestG24_StrictLatencyHardFails",
			"TestG24_CheckHookNeverBlocksOnLatency",
			"TestG24_CINoBudgetNoLatencyFinding",
		},
		Package: "main",
	},
	{
		ID:          "G25",
		Name:        "Evidence provenance fields",
		Verifies:    "Kern 2.0 evidence provenance fields",
		Enforcement: "info",
		TestFile:    "cmd/blueprint/g25_test.go",
		TestFuncs: []string{
			"TestG25_CIArtifactCarriesProvenanceFields",
			"TestG25_CheckJSONIncludesProvenanceFields",
			"TestG25_FindingJSONOmitsZeroValueProvenance",
		},
		Package: "main",
	},
	{
		ID:          "G26",
		Name:        "Sandbox tests opt-in",
		Verifies:    "Sandbox build/test check behind --tests opt-in",
		Enforcement: "block",
		TestFile:    "cmd/blueprint/g26_test.go",
		TestFuncs: []string{
			"TestG26_SandboxTestsOptIn",
		},
		Package: "main",
	},
	{
		ID:          "G27",
		Name:        "Audit chain linked to kern",
		Verifies:    "audit chain linked to kern's tamper-evident chain via kern audit append",
		Enforcement: "block",
		TestFile:    "cmd/blueprint/g27_test.go",
		TestFuncs: []string{
			"TestG27_AuditChainLinked",
		},
		Package: "main",
	},
	{
		ID:          "G28",
		Name:        "Repair loop via MCP",
		Verifies:    "Repair-loop end-to-end via MCP repair_guidance tool",
		Enforcement: "block",
		TestFile:    "internal/blueprint/mcp/g28_test.go",
		TestFuncs: []string{
			"TestG28_RepairLoopEndToEnd",
			"TestG28_ToolListIncludesRepairGuidance",
		},
		Package: "mcp",
	},
	{
		ID:          "G29",
		Name:        "Approval gate (two-person rule)",
		Verifies:    "high-risk agent changes require explicit human approval before proceeding",
		Enforcement: "block",
		TestFile:    "cmd/blueprint/approval_cmd_test.go",
		TestFuncs: []string{
			"TestP13_ApprovalGateE2E",
			"TestP13_HumanSourceNotGated",
			"TestPassLowRisk",
			"TestPassLowRiskEvenWithApprovalID",
			"TestBlockNoApprovalID",
			"TestBlockPendingApproval",
			"TestBlockRejectedApproval",
			"TestBlockUnknownApprovalID",
			"TestPassApproved",
			"TestMediumRiskHumanDoesNotRequireApproval",
			"TestRequireApprovalForOverride",
			"TestSourceNotInRequireForSourcesPasses",
		},
		Package: "main",
	},
}
